"""Expansion tactics for the B. Symbolic marketing master repository.

Each tactic is a tuple: (Channel / Tactic, Cost, Trades Relevance, In-House?, Notes)
  Cost:     "$" low/DIY · "$$" mid (paid campaigns) · "$$$" high (broadcast/large OOH)
  Relevance: High / Med / Low  — relevance to a local trades / home-services business
  In-House?: Yes = producible with B. Symbolic's own printers / AI / tools
Ratings mirror the original workbook's conventions and lens (Palm Beach County trades).

Two structures:
  EXPANSIONS      -> extra tactics appended to EXISTING categories
  NEW_CATEGORIES  -> brand-new categories (full tactic lists)

Category display metadata lives in build_master.py.
"""

# --------------------------------------------------------------------------- #
# EXTRA tactics appended to EXISTING categories (keyed by master category name)
# --------------------------------------------------------------------------- #
EXPANSIONS = {
    "Local & Direct": [
        ("EDDM (Every Door Direct Mail)", "$", "High", "No", "USPS saturation by carrier route - cheap, no list needed"),
        ("Direct-mail postcards", "$", "High", "No", "Around completed jobs / target ZIPs"),
        ("Direct-mail letters / self-mailers", "$", "Med", "No", ""),
        ("Dimensional / 3D mailers", "$$", "Med", "Yes", "Print a small item to boost open rates"),
        ("Handwritten / robo-handwritten notes", "$", "High", "No", "High response for thank-you / follow-up"),
        ("Shared mail (Valpak / Money Mailer)", "$", "High", "No", "Coupon co-op envelope"),
        ("Newspaper insert / marriage mail", "$", "Med", "No", ""),
        ("Door-knocking / canvassing", "$", "High", "Yes", "Free; target neighborhoods around jobs"),
        ("Yard signs at job sites", "$", "High", "Yes", "Cheap saturation - vinyl cutter"),
        ("Bandit / roadside signs", "$", "Med", "Yes", "Check local sign ordinances first"),
        ("Field / fence sponsorship signage", "$", "High", "Yes", "Little League outfield boards"),
        ("Community bulletin-board flyers", "$", "Med", "Yes", "Laundromats, cafes, hardware stores"),
        ("Nextdoor Business posting", "$", "High", "No", "Hyper-local, trust-based"),
        ("Local Facebook-group participation", "$", "High", "Yes", "'Who's a good plumber?' threads"),
        ("New-mover / welcome-wagon mail", "$", "High", "No", "New homeowners = new problems"),
        ("Local coupon books / value packs", "$", "Med", "No", ""),
        ("Chamber of Commerce membership", "$", "High", "No", "Referrals + local trust"),
        ("Geofencing / geo-targeted mobile ads", "$", "High", "No", "Fence competitors + neighborhoods"),
        ("Local citation / directory listings", "$", "Med", "No", "NAP consistency for local SEO"),
        ("Waze local navigation ads", "$", "High", "No", "Reach drivers in your service area"),
    ],
    "Digital - Other": [
        ("Retargeting / remarketing display", "$", "High", "No", "Cheap re-touch of site visitors"),
        ("Programmatic display ads", "$$", "Med", "No", "Automated banner buying"),
        ("Native advertising", "$$", "Low", "No", "In-feed sponsored units"),
        ("Sponsored content / advertorial", "$$", "Low", "No", ""),
        ("QR-code campaigns", "$", "Med", "Yes", "Bridge print/vehicle to landing pages"),
        ("Web-push retargeting", "$", "Med", "Yes", "Re-engage without email"),
        ("Google Screened / Guaranteed", "$", "High", "No", "Verified badge for trades"),
        ("Modernize / Networx / CraftJack", "$$", "High", "No", "Pay-per-lead home-services networks"),
        ("Waze / Apple Business Connect", "$", "Med", "No", "Map + navigation presence"),
        ("Geofence-to-mobile display", "$", "High", "No", "Target competitor lots / neighborhoods"),
        ("Connected-car / in-dash ads", "$$", "Low", "No", "Emerging"),
        ("Daily-deal / group-buying", "$", "Low", "No", "Usually low-margin"),
    ],
    "Partnership & Channel": [
        ("Pest-control cross-referral", "$", "High", "No", "Shared homeowner base"),
        ("Pool-service partnership", "$", "High", "No", "Water + pool overlap"),
        ("Landscaper / irrigation partnership", "$", "High", "No", "Backflow, hose bibs, lines"),
        ("Home-warranty company network", "$$", "High", "No", "Steady dispatched work"),
        ("Insurance-adjuster relationships", "$", "High", "No", "Water-damage claims"),
        ("Solar installer partnership", "$", "Med", "No", ""),
        ("Interior designer / remodeler", "$", "Med", "No", "Renovation plumbing"),
        ("Moving-company partnership", "$", "Med", "No", "New-home inspections"),
        ("Cleaning-service partnership", "$", "Med", "No", ""),
        ("Manufacturer co-op / MDF funds", "$", "High", "No", "Brand pays part of your ad spend"),
        ("Supply-house counter referrals", "$", "High", "No", "Ferguson/pro-desk relationships"),
        ("Bundled-service offers", "$", "Med", "Yes", "Package with an HVAC partner"),
        ("Affinity / HOA group discounts", "$", "High", "No", "Whole-community deals"),
        ("Appliance-store partnership", "$", "Med", "No", "Install referrals"),
    ],
    "Emerging / Niche": [
        ("Programmatic DOOH", "$$", "Med", "No", "Automated digital billboard buying"),
        ("Retail media networks", "$$", "Low", "No", "Amazon/Walmart ad platforms"),
        ("Self-serve CTV / OTT", "$$", "Med", "No", "Small-budget streaming TV"),
        ("Digital twins / 3D job scanning", "$", "Med", "Yes", "Scan a job to auto-generate a quote"),
        ("AI content generation", "$", "High", "Yes", "Your moat - build vs. buy"),
        ("AI image / video generation", "$", "High", "Yes", "Cheap ad + explainer creative"),
        ("AI auto-SEO / auto-optimization", "$", "High", "Yes", ""),
        ("Smart-home / IoT integration", "$", "Med", "Yes", "Leak-sensor monitoring upsell"),
        ("Gamified lead capture", "$", "Med", "Yes", "Spin-to-win / quiz-to-quote"),
        ("Live shopping / social commerce", "$", "Low", "No", "Product-oriented"),
        ("Voice commerce / smart-speaker", "$", "Low", "Yes", "Alexa skill for booking"),
        ("Hyperlocal programmatic", "$", "Med", "No", "Neighborhood-level targeting"),
        ("Metaverse / virtual worlds", "$$", "Low", "No", "Watch, don't invest"),
        ("NFT / Web3 loyalty", "$$", "Low", "No", "Skip for trades"),
    ],
}

# --------------------------------------------------------------------------- #
# NEW categories (full tactic lists). Order here = tab order after the originals.
# --------------------------------------------------------------------------- #
NEW_CATEGORIES = {
    "Email, SMS & Lifecycle": [
        ("Welcome / onboarding email series", "$", "High", "Yes", "Auto-send after first contact"),
        ("Promotional / offer email blasts", "$", "High", "No", "Seasonal specials"),
        ("Monthly newsletter", "$", "Med", "Yes", "Tips + offers to stay top-of-mind"),
        ("Seasonal campaign emails", "$", "High", "Yes", "Hurricane prep, spring tune-up"),
        ("Abandoned-quote follow-up sequence", "$", "High", "Yes", "Recover un-booked estimates"),
        ("Re-engagement / win-back series", "$", "Med", "Yes", "Reactivate cold customers"),
        ("Post-job review-request email", "$", "High", "Yes", "Automate right after completion"),
        ("Maintenance-reminder emails", "$", "High", "Yes", "Annual water-heater flush, filter swap"),
        ("Appointment confirmation / reminder emails", "$", "High", "No", "Cut no-shows"),
        ("Transactional emails (receipts/invoices)", "$", "High", "No", "Branded touchpoints"),
        ("Drip nurture sequences", "$", "High", "Yes", "Educate until ready to buy"),
        ("Lead-magnet delivery emails", "$", "High", "Yes", "Deliver the checklist/guide"),
        ("Referral-ask emails", "$", "High", "Yes", "Cheapest high-trust leads"),
        ("Birthday / anniversary emails", "$", "Low", "Yes", ""),
        ("List segmentation", "$", "High", "No", "Right message to right segment"),
        ("A/B subject-line testing", "$", "Med", "No", ""),
        ("Email deliverability / domain warmup", "$", "Med", "No", "SPF/DKIM/DMARC"),
        ("Email automation platform (Klaviyo/HubSpot)", "$$", "High", "No", "Engine for all of the above"),
        ("SMS appointment reminders", "$", "High", "No", "Highest open rate channel"),
        ("SMS promotional blasts", "$", "Med", "No", "TCPA opt-in required"),
        ("Two-way conversational SMS", "$", "High", "Yes", "Text-to-book, quick replies"),
        ("Missed-call text-back", "$", "High", "Yes", "Auto-text missed callers instantly"),
        ("MMS coupons / photo texts", "$", "Med", "No", ""),
        ("SMS keyword campaigns", "$", "Med", "No", "'Text QUOTE to 555...'"),
        ("RCS business messaging", "$", "Med", "No", "Rich Android messaging - emerging"),
        ("WhatsApp Business messaging", "$", "Low", "No", "Strong with Hispanic market"),
        ("Ringless voicemail drops", "$", "Med", "No", "Check compliance"),
        ("Web / app push notifications", "$", "Med", "No", ""),
        ("Cold email outreach (B2B)", "$", "Med", "No", "Property managers, GCs"),
        ("Interactive / AMP emails", "$", "Low", "Yes", "Book inside the email - AI edge"),
        ("Personalized dynamic-content emails", "$", "Med", "Yes", ""),
        ("Loyalty / VIP email tier", "$", "Med", "Yes", ""),
        ("List-building lead magnets", "$", "High", "Yes", "Grow the owned audience"),
    ],
    "Content Marketing & SEO": [
        ("Blog articles / how-to guides", "$", "High", "Yes", "Answer real customer questions"),
        ("Pillar pages / topic clusters", "$", "High", "Yes", "Own a topic end-to-end"),
        ("Keyword research", "$", "High", "Yes", "Find what customers search"),
        ("On-page SEO optimization", "$", "High", "Yes", "Titles, headers, intent match"),
        ("Technical SEO audit", "$", "High", "No", "Crawlability, indexation"),
        ("Core Web Vitals / speed", "$", "Med", "Yes", "Ranking + conversion factor"),
        ("Schema / structured-data markup", "$", "High", "Yes", "LocalBusiness, FAQ, Review schema"),
        ("Local SEO / NAP citations", "$", "High", "No", "Consistency across the web"),
        ("Google Business Profile optimization", "$", "High", "No", "Drives the map pack - #1 local lever"),
        ("Backlink / link-building outreach", "$", "Med", "No", "Authority signals"),
        ("Guest posting", "$", "Med", "Yes", "Links + reach"),
        ("Digital PR for links", "$$", "Med", "No", "Data studies, expert quotes"),
        ("City / neighborhood landing-page SEO", "$", "High", "Yes", "One page per PBC city"),
        ("FAQ / Q&A content", "$", "High", "Yes", "Wins voice + featured snippets"),
        ("Cost / pricing-guide content", "$", "High", "Yes", "'Repiping cost in Florida'"),
        ("Comparison content ('X vs Y')", "$", "High", "Yes", "High-intent decision stage"),
        ("Case studies / project write-ups", "$", "High", "Yes", "Proof + long-tail keywords"),
        ("Checklists / templates", "$", "High", "Yes", "Hurricane-prep plumbing checklist"),
        ("Downloadable guides / ebooks", "$", "Med", "Yes", "Lead magnets"),
        ("Infographics", "$", "Med", "Yes", "Shareable, linkable"),
        ("Video SEO / YouTube optimization", "$", "Med", "Yes", "Rank how-to videos"),
        ("Image SEO / alt text", "$", "Med", "Yes", "Job photos rank in image search"),
        ("Internal linking strategy", "$", "Med", "Yes", ""),
        ("Content refresh / historical optimization", "$", "High", "Yes", "Update old posts for fresh ranks"),
        ("Featured-snippet optimization", "$", "High", "Yes", "Position zero"),
        ("E-E-A-T / author authority", "$", "Med", "Yes", "Expertise signals"),
        ("Spanish-language SEO content", "$", "High", "Yes", "Large PBC Hispanic market"),
        ("Editorial calendar / content ops", "$", "High", "Yes", "Consistency compounds"),
        ("Reviews / testimonials pages", "$", "High", "Yes", "Trust + long-tail"),
        ("Glossary / definition content", "$", "Med", "Yes", ""),
        ("Niche / industry directory citations", "$", "Med", "No", ""),
    ],
    "Video, CTV & Streaming": [
        ("Explainer / brand videos", "$", "High", "Yes", "AI-generated cheaply"),
        ("Customer testimonial videos", "$", "High", "Yes", "Highest-trust content"),
        ("Before/after transformation videos", "$", "High", "Yes", "Show the work"),
        ("Job walkthrough / process videos", "$", "High", "Yes", "Build confidence pre-sale"),
        ("Short-form vertical video (Reels/TikTok/Shorts)", "$", "High", "Yes", "Organic reach engine"),
        ("FAQ answer videos", "$", "High", "Yes", "Repurpose to SEO + social"),
        ("YouTube channel (organic)", "$", "High", "Yes", "Evergreen how-to library"),
        ("Behind-the-scenes / team videos", "$", "Med", "Yes", "Humanize the brand"),
        ("Drone / aerial footage", "$", "Med", "Yes", "Property + job context"),
        ("Animated / motion-graphic ads", "$", "Med", "Yes", "AI motion tools"),
        ("Live streaming (FB/YT/IG Live)", "$", "Med", "Yes", "Q&A, live demos"),
        ("Webinar / live demo", "$", "Med", "Yes", "Water-quality test live"),
        ("Personalized / video email", "$", "Med", "Yes", "Stand out in the inbox"),
        ("YouTube TrueView / in-stream ads", "$$", "Med", "No", "Skippable pre-roll"),
        ("YouTube bumper ads (6s)", "$$", "Med", "No", "Cheap reach + frequency"),
        ("YouTube Shorts ads", "$$", "Med", "No", ""),
        ("Connected TV (CTV) ads", "$$", "Med", "No", "Roku/FireTV, geo-target the DMA"),
        ("OTT streaming ads (Hulu/Peacock)", "$$", "Med", "No", "TV impact, digital targeting"),
        ("Programmatic video ads", "$$", "Med", "No", ""),
        ("Paid social video ads", "$$", "High", "No", "Video outperforms static"),
        ("Product / service demo videos", "$", "High", "Yes", ""),
        ("Shoppable / interactive video", "$", "Low", "Yes", ""),
        ("Video testimonials on GBP", "$", "High", "Yes", "Boost map-pack conversion"),
        ("360 / VR walkthrough video", "$$", "Low", "No", "Niche"),
    ],
    "Audio & Podcast": [
        ("Spotify / streaming audio ads", "$$", "Med", "No", "Geo + demo targeting"),
        ("Pandora audio ads", "$$", "Med", "No", ""),
        ("iHeart / programmatic audio", "$$", "Med", "No", ""),
        ("Podcast host-read ads", "$$", "Med", "No", "Trusted-voice endorsement"),
        ("Podcast sponsorship", "$$", "Med", "No", "Local / home-improvement shows"),
        ("Launch your own podcast", "$", "Med", "Yes", "Authority + repurposable content"),
        ("Guest on local podcasts", "$", "Med", "Yes", "Free reach + backlinks"),
        ("Local radio show sponsorship", "$$", "High", "No", "Home / trades segments"),
        ("Local radio spots", "$$", "Med", "No", "Zoned to the market"),
        ("Traffic / weather sponsorship", "$$", "High", "No", "High-frequency mention"),
        ("Spanish-language radio", "$$", "High", "No", "Large PBC audience"),
        ("Radio remote / live at events", "$$", "Med", "No", ""),
        ("On-hold / call-waiting audio", "$", "Med", "Yes", "Every hold = a mini-ad"),
        ("IVR / phone-tree branding", "$", "Med", "Yes", ""),
        ("Branded audio / jingle", "$", "Med", "Yes", "Memorable sonic hook"),
        ("Voice-search optimization", "$", "High", "Yes", "'Plumber near me' voice queries"),
        ("Smart-speaker skill (Alexa/Google)", "$", "Low", "Yes", "AI edge - booking by voice"),
        ("SiriusXM ads", "$$", "Low", "No", ""),
        ("Audiobook / Audible ads", "$$", "Low", "No", ""),
        ("Twitch / gaming audio ads", "$$", "Low", "No", "Younger skew"),
    ],
    "Influencer & Creator": [
        ("Nano-influencer partnerships", "$", "Med", "No", "Local micro-audiences, cheap"),
        ("Micro-influencer campaigns", "$", "Med", "No", "Better ROI than macro"),
        ("Local lifestyle influencer collabs", "$", "Med", "No", "PBC lifestyle accounts"),
        ("Real-estate influencer collabs", "$", "High", "No", "Perfectly aligned audience"),
        ("Home / DIY creator partnerships", "$$", "Med", "No", ""),
        ("UGC creator content (paid)", "$", "High", "No", "Buy authentic video for ads"),
        ("Brand-ambassador program", "$", "Med", "Yes", "Happy customers as advocates"),
        ("Employee advocacy / staff creators", "$", "High", "Yes", "Free, authentic reach"),
        ("Creator whitelisting / Spark Ads", "$$", "Med", "No", "Run ads from creator handles"),
        ("Gifting / product seeding", "$", "Low", "Yes", "Free service for content"),
        ("Local celebrity / figure endorsement", "$$", "Med", "No", ""),
        ("Nextdoor / neighborhood advocates", "$", "High", "No", "Trusted local recommenders"),
        ("Review-video creators", "$", "Med", "No", ""),
        ("Affiliate influencers (perf-based)", "$", "Med", "No", "Pay per result"),
        ("Trade / contractor creators", "$", "Low", "No", "B2B niche"),
        ("Meme / niche-page shoutouts", "$", "Low", "No", "Cheap awareness"),
        ("Influencer event hosting", "$$", "Low", "No", ""),
        ("Podcast-host partnership", "$$", "Med", "No", ""),
    ],
    "Loyalty, Retention & Community": [
        ("Service maintenance plans", "$", "High", "No", "Recurring revenue + retention"),
        ("VIP / membership program", "$", "High", "Yes", "Annual plan with perks"),
        ("Loyalty / points program", "$", "Med", "Yes", ""),
        ("Referral rewards program", "$", "High", "Yes", "Cheapest high-trust leads"),
        ("Win-back / reactivation campaigns", "$", "High", "No", "Mine the dormant list"),
        ("Subscription / recurring service", "$", "High", "No", "Filter changes, inspections"),
        ("Post-service check-in calls", "$", "High", "Yes", "Catch issues + reviews"),
        ("NPS / satisfaction surveys", "$", "High", "Yes", "Route promoters to reviews"),
        ("Warranty registration / follow-up", "$", "High", "Yes", "Data + re-contact reason"),
        ("Customer-appreciation events", "$", "Med", "Yes", ""),
        ("Surprise-and-delight gifts", "$", "Med", "Yes", "3D-printed branded gift"),
        ("Birthday / holiday cards", "$", "Med", "Yes", "Printed in-house"),
        ("Exclusive customer community group", "$", "Med", "Yes", "Facebook/close community"),
        ("Referral leaderboard / gamification", "$", "Med", "Yes", ""),
        ("Membership perks / partner discounts", "$", "Med", "No", ""),
        ("Reviews-to-loyalty loop", "$", "High", "Yes", "Reward reviewers"),
        ("Win-back SMS", "$", "High", "No", ""),
        ("Tiered rewards / status", "$", "Low", "Yes", ""),
        ("Customer newsletter", "$", "Med", "Yes", "Retention + upsell"),
        ("Community / cause sponsorship", "$", "Med", "No", "Local goodwill"),
    ],
    "Web, CRO & UX": [
        ("Website design / redesign", "$$", "High", "Yes", "Your #1 owned asset"),
        ("Mobile-responsive optimization", "$", "High", "Yes", "Most local traffic is mobile"),
        ("Conversion-rate optimization (CRO)", "$", "High", "Yes", "More leads from same traffic"),
        ("A/B & multivariate testing", "$", "High", "Yes", ""),
        ("Heatmaps / session recording", "$", "Med", "Yes", "Hotjar / MS Clarity (free)"),
        ("Live chat / AI chatbot", "$", "High", "Yes", "24/7 lead capture - AI edge"),
        ("Click-to-call / mobile call bar", "$", "High", "Yes", "Sticky CTA on mobile"),
        ("Online booking / scheduling", "$", "High", "No", "Book without a phone call"),
        ("Instant-quote calculator", "$", "High", "Yes", "Build it - competitors buy it"),
        ("Web forms / lead capture", "$", "High", "Yes", ""),
        ("Exit-intent popups", "$", "Med", "Yes", "Catch abandoning visitors"),
        ("Trust badges / review widgets", "$", "High", "Yes", "Licenses, warranties, ratings"),
        ("Page-speed optimization", "$", "Med", "Yes", "Speed = conversions"),
        ("ADA / accessibility compliance", "$", "Med", "No", "Reduce legal risk"),
        ("Multilingual / Spanish site version", "$", "High", "Yes", "Serve the whole market"),
        ("Personalization / dynamic content", "$", "Med", "Yes", "By city/service/source"),
        ("Form analytics / drop-off tracking", "$", "Med", "Yes", ""),
        ("Landing-page builder + testing", "$", "High", "Yes", "One per campaign"),
        ("Progressive web app (PWA)", "$", "Low", "Yes", "App-like without an app"),
        ("Sticky CTA / floating quote button", "$", "High", "Yes", ""),
    ],
    "Sales Enablement & Lead Mgmt": [
        ("CRM setup / pipeline", "$", "High", "Yes", "Single source of truth"),
        ("Call tracking (CallRail)", "$", "High", "No", "Attribute every call to a source"),
        ("Lead-scoring automation", "$", "High", "Yes", "Prioritize hot leads"),
        ("Speed-to-lead automation", "$", "High", "Yes", "Contact within 5 min = 10x close"),
        ("Automated follow-up sequences", "$", "High", "Yes", "No lead left behind"),
        ("Quote / estimate software", "$", "High", "No", "Faster, more pro estimates"),
        ("Proposal / e-signature tools", "$", "High", "No", "Close on the spot"),
        ("Sales scripts / playbooks", "$", "High", "Yes", "Consistent objection handling"),
        ("Appointment scheduling / dispatch", "$", "High", "No", ""),
        ("Missed-call text-back", "$", "High", "Yes", "Recover missed opportunities"),
        ("Live-chat-to-CRM routing", "$", "High", "Yes", ""),
        ("Sales collateral / one-sheets", "$", "High", "Yes", "Printed in-house"),
        ("Financing offers / integration", "$", "High", "No", "Bigger tickets close easier"),
        ("Review-request automation", "$", "High", "Yes", "Compound your reputation"),
        ("Reputation-management dashboard", "$", "High", "No", "Monitor + respond everywhere"),
        ("Dead-lead reactivation database", "$", "High", "Yes", "Goldmine of old quotes"),
        ("Upsell / cross-sell prompts", "$", "High", "Yes", "Filter, warranty, membership"),
        ("Sales dashboards / reporting", "$", "Med", "Yes", ""),
        ("Territory / route optimization", "$", "Med", "Yes", "More jobs per truck-day"),
        ("Win/loss analysis", "$", "Med", "Yes", "Learn why quotes lose"),
    ],
    "Analytics, Data & MarTech": [
        ("Google Analytics 4", "$", "High", "Yes", "Free; measure everything"),
        ("Google Tag Manager", "$", "High", "Yes", "Manage tags without a dev"),
        ("Conversion tracking / pixels", "$", "High", "Yes", "Know what actually converts"),
        ("Call-tracking analytics", "$", "High", "No", "Phone is the trades' main channel"),
        ("UTM tagging / campaign tracking", "$", "High", "Yes", "Attribute every link"),
        ("Attribution modeling", "$", "Med", "Yes", "Credit the right channels"),
        ("Marketing dashboard (Looker Studio)", "$", "Med", "Yes", "Free; one-glance ROI"),
        ("Server-side tracking / CAPI", "$", "Med", "Yes", "Recover lost signal"),
        ("Retargeting / pixel audiences", "$", "High", "Yes", ""),
        ("Lookalike audience building", "$", "Med", "No", "Scale from best customers"),
        ("Rank tracking / SEO tools", "$", "High", "Yes", "SEMrush / Ahrefs"),
        ("Social listening / monitoring", "$", "Med", "Yes", "Catch mentions + complaints"),
        ("Review monitoring / alerts", "$", "High", "Yes", "Respond fast"),
        ("Competitor analysis tools", "$", "Med", "Yes", ""),
        ("Marketing automation platform", "$$", "High", "No", "Ties channels together"),
        ("Customer data platform (CDP)", "$$", "Low", "No", "Overkill for most local biz"),
        ("First-party data collection", "$", "High", "Yes", "Own your audience"),
        ("ROI / ROAS reporting", "$", "High", "Yes", "Kill what doesn't pay"),
        ("Predictive analytics / AI lead scoring", "$", "High", "Yes", "Your AI moat"),
        ("Consent / privacy management", "$", "Med", "No", "TCPA / cookie compliance"),
        ("Cohort / retention analysis", "$", "Med", "Yes", ""),
        ("Data enrichment / lead append", "$", "Med", "No", ""),
        ("Spreadsheet / BI reporting", "$", "High", "Yes", "Cheap, flexible"),
    ],
    "Branding, Creative & Design": [
        ("Logo design / refresh", "$", "High", "Yes", ""),
        ("Brand identity / style guide", "$", "High", "Yes", "Consistency = recognition"),
        ("Brand voice / messaging framework", "$", "High", "Yes", "How you sound everywhere"),
        ("Tagline / slogan development", "$", "Med", "Yes", ""),
        ("Color palette / typography system", "$", "Med", "Yes", ""),
        ("Brand photography", "$", "High", "No", "Real team + jobs beat stock"),
        ("Mascot / character design", "$", "Med", "Yes", "3D-printable mascot"),
        ("Uniform / apparel branding", "$", "High", "Yes", "Heat press in-house"),
        ("Vehicle-livery / wrap design", "$", "High", "Yes", "Rolling billboard"),
        ("Business-card / stationery design", "$", "High", "Yes", "Printed in-house"),
        ("Social / ad creative templates", "$", "High", "Yes", "Canva brand kit"),
        ("Signage / storefront design", "$", "Med", "Yes", ""),
        ("Packaging / label design", "$", "Med", "Yes", "Filter kits, leave-behinds"),
        ("Pitch-deck / presentation templates", "$", "Med", "Yes", "For commercial bids"),
        ("Sonic identity / jingle", "$", "Low", "Yes", ""),
        ("Icon / illustration set", "$", "Med", "Yes", ""),
        ("Brand audit / positioning", "$", "High", "No", "Find your differentiator"),
        ("Rebranding campaign", "$$", "Med", "No", ""),
        ("Trademark / brand protection", "$$", "Med", "No", "Protect the name"),
        ("Asset library / DAM", "$", "Med", "Yes", "Organize photos + creative"),
    ],
    "B2B & Account-Based": [
        ("Account-based marketing (ABM)", "$$", "Med", "No", "Target named commercial accounts"),
        ("LinkedIn Sponsored Content", "$$", "Med", "No", "Reach property/facility managers"),
        ("LinkedIn message / InMail ads", "$$", "Med", "No", ""),
        ("LinkedIn lead-gen forms", "$$", "Med", "No", ""),
        ("Cold email outreach (B2B)", "$", "Med", "No", "Sequenced, personalized"),
        ("Cold calling / outbound", "$", "Med", "Yes", "Direct to decision-makers"),
        ("Commercial property-manager outreach", "$", "High", "Yes", "Recurring contract work"),
        ("Facility-management partnerships", "$", "High", "No", ""),
        ("Government / municipal bid lists", "$", "Med", "No", "Public-works plumbing"),
        ("Trade-association membership", "$", "High", "No", "Credibility + referrals"),
        ("Industry directory listings", "$", "Med", "No", ""),
        ("Net-30 / builder accounts", "$", "High", "No", "Lock in contractor volume"),
        ("Commercial case studies", "$", "High", "Yes", "Proof for bigger buyers"),
        ("RFP / proposal response", "$", "High", "Yes", "Win contract work"),
        ("B2B webinar / lunch-and-learn", "$", "Med", "Yes", "Educate GCs / PMs"),
        ("Vendor / supplier co-marketing", "$", "Med", "No", ""),
        ("Channel-partner / reseller program", "$", "Low", "No", ""),
        ("Wholesale / distributor relationships", "$", "Med", "No", ""),
        ("Manufacturer certification / listing", "$", "High", "No", "Certified-installer directories"),
        ("Franchise / licensing marketing", "$$", "Low", "No", "Only if scaling that way"),
    ],
    "Cause, Community & CSR": [
        ("Local charity sponsorship", "$", "High", "Yes", "Goodwill + local PR"),
        ("Youth sports team sponsorship", "$", "High", "Yes", "Jersey + banner"),
        ("School / PTA sponsorship", "$", "High", "Yes", ""),
        ("Disaster-relief response", "$", "High", "Yes", "Free checks after hurricanes/boil-water"),
        ("Veteran / first-responder discount", "$", "High", "Yes", "Community trust"),
        ("Cause-marketing campaign", "$", "Med", "Yes", "Free water tests for schools"),
        ("Community education workshops", "$", "High", "Yes", "Home-readiness clinics"),
        ("Sustainability / green messaging", "$", "Med", "Yes", "Water conservation angle"),
        ("Nonprofit partnership", "$", "Med", "Yes", ""),
        ("Volunteer / service days", "$", "Med", "Yes", "Team + content"),
        ("Adopt-a-road / park cleanup", "$", "Med", "Yes", "Roadside recognition sign"),
        ("Food drive / donation matching", "$", "Med", "Yes", ""),
        ("Scholarship / trade-grant program", "$", "Low", "Yes", "Workforce goodwill"),
        ("Local business alliance / chamber", "$", "High", "No", "Referrals + credibility"),
        ("Faith / civic group sponsorship", "$", "Med", "No", ""),
    ],
}

# New-category display metadata: master_name -> (excel_tab_title <=31 chars, TITLE BAND)
NEW_CATEGORY_META = {
    "Email, SMS & Lifecycle":        ("Email SMS and Lifecycle",   "EMAIL, SMS & LIFECYCLE"),
    "Content Marketing & SEO":       ("Content Marketing and SEO", "CONTENT MARKETING & SEO"),
    "Video, CTV & Streaming":        ("Video CTV and Streaming",   "VIDEO, CTV & STREAMING"),
    "Audio & Podcast":               ("Audio and Podcast",         "AUDIO & PODCAST"),
    "Influencer & Creator":          ("Influencer and Creator",    "INFLUENCER & CREATOR"),
    "Loyalty, Retention & Community": ("Loyalty and Retention",    "LOYALTY, RETENTION & COMMUNITY"),
    "Web, CRO & UX":                 ("Web CRO and UX",            "WEB, CRO & UX"),
    "Sales Enablement & Lead Mgmt":  ("Sales Enablement",          "SALES ENABLEMENT & LEAD MGMT"),
    "Analytics, Data & MarTech":     ("Analytics and MarTech",     "ANALYTICS, DATA & MARTECH"),
    "Branding, Creative & Design":   ("Branding and Creative",     "BRANDING, CREATIVE & DESIGN"),
    "B2B & Account-Based":           ("B2B and Account-Based",     "B2B & ACCOUNT-BASED"),
    "Cause, Community & CSR":         ("Cause and Community",       "CAUSE, COMMUNITY & CSR"),
}

# Order of new categories as they should appear after the 13 originals.
NEW_CATEGORY_ORDER = [
    "Email, SMS & Lifecycle",
    "Content Marketing & SEO",
    "Video, CTV & Streaming",
    "Audio & Podcast",
    "Influencer & Creator",
    "Loyalty, Retention & Community",
    "Web, CRO & UX",
    "Sales Enablement & Lead Mgmt",
    "Analytics, Data & MarTech",
    "Branding, Creative & Design",
    "B2B & Account-Based",
    "Cause, Community & CSR",
]
