"""National seed dataset: billboard / OOH companies across the top-10 US cities.

Top-10 US cities by population (city proper): New York, Los Angeles, Chicago,
Houston, Phoenix, Philadelphia, San Antonio, San Diego, Dallas, Jacksonville.

Compiled from public web sources on 2026-07-08 (company sites, market listings,
industry directories). Same caveat as the Florida seed: this is a real, usable
starting list, not the exhaustive permit-level roster — there is no single
national equivalent of Florida's FDOT licensee database, so local operators are
gathered market by market.

For the national workbook the Company fields are repurposed:
  * counties_served     -> which of the top-10 cities the company serves
  * serves_palm_beach   -> "Yes" = national / multi-market operator (highlighted)
  * city / state        -> the company's HQ / main office
Header labels are overridden accordingly in build_national().
"""
from __future__ import annotations

from typing import List

from .models import (
    Company,
    TYPE_NATIONAL,
    TYPE_REGIONAL,
    TYPE_INDEPENDENT,
    TYPE_MOBILE,
    TYPE_BROKER,
)

TOP_CITIES = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "Jacksonville",
]

_REF = "Static ~$1k–$25k+/4wk; premium/spectacular boards much higher (market avg)"

# Header overrides so the repurposed columns read correctly in the workbook/CSV.
HEADER_OVERRIDES = {
    "counties_served": "Top-10 Cities Served",
    "serves_palm_beach": "National / multi-market",
    "city": "HQ City",
    "state": "HQ State",
    "primary_market": "Primary Market(s)",
}


NATIONAL_SEED: List[Company] = [
    # ------------------------------------------------------------------ #
    # THE BIG THREE — present in essentially every top-10 city
    # ------------------------------------------------------------------ #
    Company(
        company_name="Lamar Advertising",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (largest US billboard network)",
        counties_served="Los Angeles; Houston; Phoenix; San Antonio; San Diego; Dallas; Jacksonville (+ most US metros)",
        serves_palm_beach="Yes",
        city="Baton Rouge",
        state="LA",
        website="https://lamar.com/",
        pricing_reference=_REF,
        notes="Largest US OOH operator; ~350k+ displays. Strong in LA, TX, AZ, San Diego (I-5/I-805/I-15/Hwy 78), Jacksonville.",
        source="lamar.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Clear Channel Outdoor",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (top-3 US operator)",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        city="San Antonio",
        state="TX",
        website="https://clearchanneloutdoor.com/",
        pricing_reference=_REF,
        notes="Big-three operator; ~$2.1B revenue. e.g. Phoenix ~500 displays reaching 88% of adults 18+ weekly.",
        source="clearchanneloutdoor.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="OUTFRONT Media",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (top-3 US operator; major transit)",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.outfront.com/",
        pricing_reference=_REF,
        notes="Big-three operator; runs NYC MTA transit advertising. Billboards + transit in all top-10 markets.",
        source="outfront.com; WebSearch 2026-07-08",
        confidence="High",
    ),

    # ------------------------------------------------------------------ #
    # NATIONAL / MULTI-MARKET INDEPENDENTS & PREMIUM NETWORKS
    # ------------------------------------------------------------------ #
    Company(
        company_name="New Tradition Media",
        company_type=TYPE_NATIONAL,
        primary_market="Premium spectaculars: NYC Times Sq, LA Hollywood, Chicago",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="Chicago",
        state="IL",
        website="https://www.newtradition.com/",
        pricing_reference="Premium / spectacular placements — quote only, high-end",
        notes="Large-format 'spectacular' billboards in marquee locations (Times Square, Hollywood).",
        source="newtradition.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Capitol Outdoor",
        company_type=TYPE_NATIONAL,
        primary_market="Chicago; Los Angeles; Manhattan; Philadelphia; San Diego; Miami",
        counties_served="New York; Los Angeles; Chicago; Philadelphia; San Diego",
        serves_palm_beach="Yes",
        website="https://capitoloutdoor.com/",
        pricing_reference=_REF,
        notes="Digital billboards, kiosks, wallscapes across major markets.",
        source="capitoloutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Brooklyn Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA; Los Angeles; Chicago",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://brooklynoutdoor.com/",
        pricing_reference=_REF,
        notes="Woman-owned OOH firm; billboards, wallscapes, experiential.",
        source="brooklynoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Digital Outdoor Advertising, LLC",
        company_type=TYPE_NATIONAL,
        primary_market="Coast-to-coast digital network (200+ markets)",
        counties_served="Philadelphia; Jacksonville (+ 200 US markets)",
        serves_palm_beach="Yes",
        website="https://digitaloutdooradvertising.com/",
        pricing_reference=_REF,
        notes="20,000+ digital & static billboards across 200+ markets incl. Philadelphia and Jacksonville.",
        source="digitaloutdooradvertising.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Becker Boards",
        company_type=TYPE_REGIONAL,
        primary_market="Phoenix (+ SF, Miami, Ft. Lauderdale, Orlando, Chicago)",
        counties_served="Phoenix; Chicago",
        serves_palm_beach="Yes",
        city="Phoenix",
        state="AZ",
        website="https://www.beckerboards.com/",
        pricing_reference=_REF,
        notes="Digital, static & wallscape billboards; city-wide greater-Phoenix coverage.",
        source="beckerboards.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="AltTerrain",
        company_type=TYPE_MOBILE,
        primary_market="Mobile & street-level: NYC, Chicago, LA",
        counties_served="New York; Chicago; Los Angeles",
        serves_palm_beach="Yes",
        website="https://altterrain.com/",
        pricing_reference="Mobile / street-level placements — quote only",
        notes="Mobile billboards + street-level media (bodegas, laundromats, barbershops).",
        source="altterrain.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ------------------------------------------------------------------ #
    # TEXAS (Houston / Dallas / San Antonio)
    # ------------------------------------------------------------------ #
    Company(
        company_name="SignAd Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Texas (Houston-based) + parts of Louisiana",
        counties_served="Houston; San Antonio; Dallas",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.signad.com/",
        pricing_reference=_REF,
        notes="Largest independently owned OOH company in Texas; 2,600+ displays.",
        source="signad.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="BM Outdoor Media",
        company_type=TYPE_REGIONAL,
        primary_market="44 Texas cities + Phoenix",
        counties_served="Houston; Dallas; San Antonio; Phoenix",
        serves_palm_beach="No",
        website="https://bmoutdoor.com/",
        pricing_reference=_REF,
        notes="Billboards, digital, transit & street furniture across 44 TX cities and Phoenix.",
        source="bmoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Lux Media",
        company_type=TYPE_MOBILE,
        primary_market="Dallas; Houston; Austin; San Antonio",
        counties_served="Houston; San Antonio; Dallas",
        serves_palm_beach="No",
        website="https://www.luxmediaads.com/",
        pricing_reference="Mobile LED truck — day/route rate, quote only",
        notes="Mobile LED billboard truck advertising across major TX metros.",
        source="luxmediaads.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Billboards America",
        company_type=TYPE_BROKER,
        primary_market="Texas (Dallas, Houston, Austin, San Antonio, Fort Worth)",
        counties_served="Houston; Dallas; San Antonio",
        serves_palm_beach="No",
        website="https://www.billboardsamerica.com/billboard-advertising-locations/texas",
        pricing_reference=_REF,
        notes="Brokerage with access to prime TX billboard locations.",
        source="billboardsamerica.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Premier Mobile Billboards",
        company_type=TYPE_MOBILE,
        primary_market="Houston; Dallas; San Antonio (mobile)",
        counties_served="Houston; Dallas; San Antonio",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://premiermobilebillboards.com/",
        pricing_reference="Mobile LED truck — quote only",
        notes="Digital billboard trucks across major TX metros (Houston, Dallas, San Antonio).",
        source="premiermobilebillboards.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ------------------------------------------------------------------ #
    # PHOENIX
    # ------------------------------------------------------------------ #
    Company(
        company_name="Arizona Billboard Company",
        company_type=TYPE_INDEPENDENT,
        primary_market="Phoenix / Arizona",
        counties_served="Phoenix",
        serves_palm_beach="No",
        city="Phoenix",
        state="AZ",
        website="https://arizonabillboardcompany.com/",
        pricing_reference=_REF,
        notes="30+ yrs; billboards, digital LED, buses, shelters, airports, stadiums.",
        source="arizonabillboardcompany.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ------------------------------------------------------------------ #
    # SAN DIEGO
    # ------------------------------------------------------------------ #
    Company(
        company_name="American Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="San Diego; Phoenix",
        counties_served="San Diego; Phoenix",
        serves_palm_beach="No",
        website="https://www.americanoutdoor.com/",
        pricing_reference=_REF,
        notes="Digital & static billboards on high-traffic routes; regional operator in San Diego and Phoenix.",
        source="americanoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ------------------------------------------------------------------ #
    # JACKSONVILLE
    # ------------------------------------------------------------------ #
    Company(
        company_name="MediaLease OOH — Jacksonville",
        company_type=TYPE_REGIONAL,
        primary_market="Jacksonville",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        website="https://www.medialeaseooh.com/jacksonville-fl/",
        pricing_reference=_REF,
        notes="Digital LED + traditional billboards, bus, rail, shelter ads in Jacksonville.",
        source="medialeaseooh.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # NEW YORK CITY — deep-dive roster (highly fragmented market)
    # ================================================================== #
    Company(
        company_name="JCDecaux",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & street furniture: NYC bus shelters, JFK & LGA airports",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.jcdecaux.com/",
        pricing_reference="Street furniture / airport / transit — quote only",
        notes="Exclusive NYC bus-shelter network + JFK/LGA airport advertising; global OOH leader.",
        source="WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Branded Cities Network",
        company_type=TYPE_NATIONAL,
        primary_market="Times Square spectaculars + major-market landmarks",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        website="https://www.brandedcities.com/",
        pricing_reference="Spectacular / landmark placements — quote only, high-end",
        notes="Operates marquee Times Square spectaculars and other landmark displays.",
        source="WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Intersection",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & smart-city media (LinkNYC kiosks)",
        counties_served="New York; Chicago; Philadelphia",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.intersection.com/",
        pricing_reference="Digital kiosk / transit — quote only",
        notes="Runs LinkNYC kiosk network; transit & place-based media in multiple metros.",
        source="WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="TSX Broadway (TSX Entertainment)",
        company_type=TYPE_INDEPENDENT,
        primary_market="Times Square (single landmark asset)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference="Premium spectacular — quote only, very high-end",
        notes="Flagship 18k-sq-ft curved LED at 47th & Broadway, Times Square.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Neutron Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (digital billboards)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="Digital billboards in NYC's busiest corridors.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Heritage Outdoor Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Times Square digital)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference="Times Square digital — quote only",
        notes="Times Square LED billboard technology.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Pearl Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York / Times Square + experiential",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://pearlmedia.com/",
        pricing_reference="Times Square / experiential — quote only",
        notes="Times Square billboards and experiential activations.",
        source="pearlmedia.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Adams Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA + mid-size US markets",
        counties_served="New York",
        serves_palm_beach="No",
        pricing_reference=_REF,
        notes="Traditional + digital billboards in high-visibility locations.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Rolling Adz Mobile Billboards",
        company_type=TYPE_MOBILE,
        primary_market="New York City (mobile)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://rollingadz.com/",
        pricing_reference="Mobile billboard — day/route rate, quote only",
        notes="Mobile billboard fleet across NYC.",
        source="rollingadz.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="SILVERCAST Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (spectaculars: Times Sq, Penn Plaza, MSG)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://www.silvercastmedia.com/",
        pricing_reference="Oversized digital/static spectaculars — quote only, high-end",
        notes="Premier oversized billboard spectaculars at Times Sq, Penn Plaza & Madison Square Garden.",
        source="silvercastmedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Colossal Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Brooklyn) — hand-painted murals/wallscapes",
        counties_served="New York",
        serves_palm_beach="No",
        city="Brooklyn",
        state="NY",
        website="https://colossalmedia.com/",
        pricing_reference="Hand-painted wallscape / mural — quote only",
        notes="Specialist in hand-painted outdoor advertising & public-art wallscapes.",
        source="colossalmedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Van Wagner",
        company_type=TYPE_NATIONAL,
        primary_market="Sports & entertainment venue OOH (stadiums/arenas)",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.vanwagner.com/",
        pricing_reference="Venue / sponsorship media — quote only",
        notes="OOH inventory for stadiums, arenas and sports/entertainment facilities.",
        source="vanwagner.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Vector Media",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & experiential (buses, double-deckers)",
        counties_served="New York; Chicago; Philadelphia",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://vectormedia.com/",
        pricing_reference="Transit / experiential — quote only",
        notes="Large-format transit, double-decker buses, experiential assets across US metros.",
        source="vectormedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="PMD Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA (top-5 by spot count)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="Among the top-5 OOH owners in the NYC DMA by spot count.",
        source="oohtoday.com Top-5 NYC operators; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="InSite Street Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA (top-5 by spot count)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://www.insitestreetmedia.com/",
        pricing_reference=_REF,
        notes="Top-5 NYC DMA operator; residential & street-level media networks.",
        source="oohtoday.com Top-5 NYC operators; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Big Outdoor",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York; Philadelphia (digital spectaculars)",
        counties_served="New York; Philadelphia",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://bigoutdoor.com/",
        pricing_reference="Digital spectacular — quote only",
        notes="Digital billboard / spectacular operator (NYC + Philadelphia).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="GSB Digital",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York — wildposting / wheatpaste, print & install",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://gsbdigital.com/",
        pricing_reference="Wildposting / production — quote only",
        notes="Street-level wheatpaste/wildposting (SoHo, Williamsburg, LES, Bushwick, Harlem) + OOH production & install.",
        source="gsbdigital.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Seen Outdoor Media, LLC",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Brooklyn)",
        counties_served="New York",
        serves_palm_beach="No",
        city="Brooklyn",
        state="NY",
        pricing_reference=_REF,
        notes="On the NYC DOB Active Outdoor Advertising Companies (OAC) registry.",
        source="NYC DOB Active OAC list; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Red Rock Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Manhattan)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="On the NYC DOB Active Outdoor Advertising Companies (OAC) registry.",
        source="NYC DOB Active OAC list; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Billups",
        company_type=TYPE_BROKER,
        primary_market="National OOH agency / managed services",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        website="https://www.billups.com/",
        pricing_reference="Managed-service buying across operators — quote only",
        notes="Independent global OOH agency; plans/buys/measures across all operators & markets.",
        source="billups.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # HOUSTON — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Gilbreath Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Greater Houston + Texas Hill Country",
        counties_served="Houston; San Antonio",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.gilbreathoutdoor.com/",
        pricing_reference=_REF,
        notes="Houston-area operator with a Texas Hill Country satellite office.",
        source="gilbreathoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="MH Outdoor Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="Houston metro",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        pricing_reference=_REF,
        notes="Local Houston billboard operator.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Avail Media Group",
        company_type=TYPE_BROKER,
        primary_market="Houston (independent OOH agency)",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.availmediagroup.com/capabilities/out-of-home",
        pricing_reference="Independent agency — negotiates across vendors",
        notes="Independent agency negotiating across multiple Houston OOH vendors for placement & pricing.",
        source="availmediagroup.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Inspiria Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="Houston",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://inspiriaoutdoor.com/houston-advertising/",
        pricing_reference=_REF,
        notes="Houston billboard advertising across various outdoor formats.",
        source="inspiriaoutdoor.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # DALLAS–FORT WORTH — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Arrington Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Dallas–Fort Worth Metroplex",
        counties_served="Dallas",
        serves_palm_beach="No",
        city="Dallas",
        state="TX",
        website="https://www.arringtonoutdoor.com/",
        pricing_reference=_REF,
        notes="Largest independent billboard company in the DFW area; bulletins & digital.",
        source="arringtonoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Ralston Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Dallas–Fort Worth",
        counties_served="Dallas",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="DFW independent operator (inventory aggregated by AdQuick alongside Lamar/CCO/OUTFRONT).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Albert Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="Dallas–Fort Worth",
        counties_served="Dallas",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="DFW independent operator (named among AdQuick's aggregated DFW operators).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Dallas Billboards LLC",
        company_type=TYPE_BROKER,
        primary_market="Dallas–Fort Worth Metroplex",
        counties_served="Dallas",
        serves_palm_beach="No",
        city="Dallas",
        state="TX",
        website="https://www.dallasbillboards.com/",
        pricing_reference="Media buyer / creative agency — quote only",
        notes="Full-service OOH media buyer & creative agency securing DFW billboard locations.",
        source="dallasbillboards.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # SAN ANTONIO — deep-dive roster
    # ================================================================== #
    Company(
        company_name="True Impact Media",
        company_type=TYPE_BROKER,
        primary_market="San Antonio (+ national mobile)",
        counties_served="San Antonio",
        serves_palm_beach="No",
        website="https://trueimpactmedia.com/billboard-advertising-in-san-antonio/",
        pricing_reference="Billboards + mobile — quote only",
        notes="Comprehensive San Antonio OOH incl. static, digital and mobile billboards.",
        source="trueimpactmedia.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # LOS ANGELES — deep-dive roster (100+ independents in market)
    # ================================================================== #
    Company(
        company_name="Regency Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Los Angeles / Orange County (Sunset Strip, LAX)",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        address="8820 Sunset Blvd",
        city="West Hollywood",
        state="CA",
        zip_code="90069",
        phone="(310) 657-8883",
        website="https://regencyoutdoor.com/",
        pricing_reference="Premium bulletins/spectaculars — quote only, high-end",
        notes="Est. 1974; SoCal's foremost private OOH firm. 300+ billboards & wallscapes, "
              "dominant Sunset Strip presence + LAX exterior. (Sold 35 Strip boards to Netflix for $150M in 2018.)",
        source="regencyoutdoor.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Bulletin Displays",
        company_type=TYPE_REGIONAL,
        primary_market="Los Angeles (freeway billboards)",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        city="Los Angeles",
        state="CA",
        website="https://www.bulletindisplays.com/",
        pricing_reference=_REF,
        notes="One of the top-5 freeway billboard operators in the LA area; digital & static.",
        source="bulletindisplays.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Bray Outdoor Ads",
        company_type=TYPE_INDEPENDENT,
        primary_market="Los Angeles & San Diego counties (SoCal)",
        counties_served="Los Angeles; San Diego",
        serves_palm_beach="No",
        website="https://brayoutdoor.com/",
        pricing_reference=_REF,
        notes="SoCal billboard operator/media buyer across LA and San Diego counties.",
        source="brayoutdoor.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="O Media Group",
        company_type=TYPE_INDEPENDENT,
        primary_market="Los Angeles",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        city="Los Angeles",
        state="CA",
        pricing_reference=_REF,
        notes="LA independent OOH operator (named among Regency's LA competitors).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # CHICAGO — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Image Media Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Chicagoland",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        website="https://imageoutdoor.com/",
        pricing_reference=_REF,
        notes="Billboard, bulletin, digital & wall advertising across Chicagoland.",
        source="imageoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Outdoor Impact",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (north side)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        website="https://www.outdoorimpact.com/",
        pricing_reference=_REF,
        notes="Billboard & wall-display advertising, esp. northern Chicago.",
        source="outdoorimpact.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="VC Outdoor",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (40 neighborhoods)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference="Wildposting / wallscape / bus wrap — quote only",
        notes="Hotspots, wild postings, wallscapes, bus wraps & street furniture across 40 Chicago neighborhoods.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="GreenSigns Chicago",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (all-digital network)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference="Digital billboard — quote only",
        notes="Fully digital, eco-friendly billboard network.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="J&B Signs Inc",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference=_REF,
        notes="Independent OOH media company partnering with local/regional/national advertisers.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Red Star Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Chicago",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference=_REF,
        notes="Chicago-market billboard operator (named among major Chicago operators).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # PHILADELPHIA — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Keystone Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Philadelphia / Pennsylvania",
        counties_served="Philadelphia",
        serves_palm_beach="No",
        state="PA",
        website="https://www.keystoneoutdoor.com/",
        pricing_reference=_REF,
        notes="Regional PA billboard operator serving the Philadelphia market.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Catalyst Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Philadelphia suburbs + New York",
        counties_served="Philadelphia; New York",
        serves_palm_beach="No",
        state="PA",
        website="https://www.linkedin.com/company/catalyst-outdoor-advertising",
        pricing_reference="Digital billboards — quote only",
        notes="Founded 2009 (Thaddeus Bartkowski); ~14 digital faces, known for 'living wall' "
              "displays. NOTE: financial distress in 2024; assets reportedly being sold to "
              "Lamar & Clear Channel — verify current ownership before contacting.",
        source="Billboard Insider; Philadelphia Inquirer; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # JACKSONVILLE — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Daily Billboards",
        company_type=TYPE_INDEPENDENT,
        primary_market="Jacksonville",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        city="Jacksonville",
        state="FL",
        pricing_reference=_REF,
        notes="Independent operator with ~49 billboard locations in and around Jacksonville.",
        source="Alignable; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="American Mobile Ads",
        company_type=TYPE_MOBILE,
        primary_market="Jacksonville (mobile)",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        website="https://americanmobileads.com/markets/jacksonville",
        pricing_reference="Mobile LED truck — day/route rate, quote only",
        notes="Backlit + digital LED/video mobile billboard trucks in Jacksonville.",
        source="americanmobileads.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Fisher Design & Advertising",
        company_type=TYPE_BROKER,
        primary_market="Jacksonville (agency)",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        city="Jacksonville",
        state="FL",
        website="https://www.fisherdesignandadvertising.com/services/outdoor-advertising-jacksonville/",
        pricing_reference="Agency — books across outdoor vendors, quote only",
        notes="Agency partnering with outdoor companies for Jacksonville OOH campaigns.",
        source="fisherdesignandadvertising.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # NATIONAL BROKERS / MARKETPLACES (book inventory across all 10 cities)
    # ================================================================== #
    Company(
        company_name="AdQuick",
        company_type=TYPE_BROKER,
        primary_market="Nationwide OOH marketplace",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        website="https://www.adquick.com/",
        pricing_reference="Marketplace booking; publishes 2026 cost/CPM guides",
        notes="Aggregates operator inventory nationwide; good for live availability & pricing benchmarks.",
        source="adquick.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Blue Line Media",
        company_type=TYPE_BROKER,
        primary_market="Nationwide brokerage",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        phone="(800) 807-0360",
        email="Advertise@BlueLineMedia.com",
        website="https://www.bluelinemedia.com/",
        pricing_reference="Brokerage; publishes market rate guides",
        notes="Books static & digital billboards across operators in every major market.",
        source="bluelinemedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="BillboardsIn",
        company_type=TYPE_BROKER,
        primary_market="Nationwide OOH marketplace",
        counties_served="New York; Los Angeles; Chicago; Houston; Phoenix; Philadelphia; San Antonio; San Diego; Dallas; Jacksonville",
        serves_palm_beach="Yes",
        website="https://www.billboardsin.com/",
        pricing_reference="Marketplace booking — dynamic",
        notes="Searchable inventory marketplace across US markets.",
        source="billboardsin.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
]


# ---------------------------------------------------------------------- #
# City market ranking — by billboard market size & typical ad rates.
# Ranking is a synthesis of metro/DMA size, OOH inventory density, and the
# published rate ranges below (compiled 2026-07-08). Rates are typical monthly
# ranges for standard billboards; premium/landmark placements run far higher.
# Columns: (rank, city, state, tier, rate_low, rate_high, premium note)
# rate_low / rate_high are typical MONTHLY $ for standard billboards (numeric,
# used for the bar chart); the display string is derived from them.
# ---------------------------------------------------------------------- #
CITY_MARKET = [
    (1, "New York", "NY", "Tier 1 — largest US OOH market", 3000, 50000,
     "Times Square spectaculars $10,000 to $1,000,000+/mo; Manhattan digital $15k–$50k; outer-borough static $3k–$8k."),
    (2, "Los Angeles", "CA", "Tier 1", 2500, 40000,
     "Iconic Sunset Strip bulletins command a large multiple of comparable units 30 mi east."),
    (3, "Chicago", "IL", "Tier 1", 2000, 25000,
     "Premium expressway (Kennedy/Dan Ryan) and Loop digital displays at the high end."),
    (4, "Dallas", "TX", "Tier 2 — large metro (DFW)", 1500, 18000,
     "High-traffic corridors (I-35, LBJ, Central Expwy) priced highest."),
    (5, "Houston", "TX", "Tier 2 — large metro", 1500, 15000,
     "Clear Channel alone runs 2,000+ boards across 13 counties (99% of DMA adults)."),
    (6, "Philadelphia", "PA", "Tier 2", 1500, 12000,
     "I-95 / Schuylkill Expwy and Center City digital at the top of range."),
    (7, "Phoenix", "AZ", "Tier 2/3", 1200, 10000,
     "Freeway digital (Loop 101/202, I-10); sports-venue-adjacent units premium."),
    (8, "San Diego", "CA", "Tier 3", 1500, 10000,
     "I-5 / I-805 / I-15 / Hwy-78 corridors; limited inventory keeps rates firm."),
    (9, "San Antonio", "TX", "Tier 3", 1000, 8000,
     "I-10 / Loop 410 / US-281 the strongest placements."),
    (10, "Jacksonville", "FL", "Tier 3", 800, 6000,
     "Largest US city by land area; I-95 / I-295 corridors carry the value."),
]

CITY_RANK_DISCLAIMER = (
    "Ranking synthesizes metro/DMA size, billboard inventory density and published "
    "2026 rate guides (AdQuick, DASH TWO, CostCheck, etc.). Rates are typical MONTHLY "
    "ranges for standard billboards; premium/landmark and digital placements run far "
    "higher. Treat as directional benchmarks, not quotes."
)


def cities_for(company: Company) -> List[str]:
    """Which of the top-10 cities a company serves (from its coverage field)."""
    coverage = (company.counties_served or "")
    return [c for c in TOP_CITIES if c in coverage]


def load_national() -> List[Company]:
    return [Company(**{k: v for k, v in vars(c).items()}) for c in NATIONAL_SEED]
