"""National seed dataset: billboard / OOH companies across 26 major US metros.

Markets (market-size rank order): New York, Los Angeles, Chicago, San Francisco,
Atlanta, Washington DC, Boston, Dallas, Houston, Miami, Philadelphia, Detroit,
Seattle, Minneapolis, Phoenix, Tampa, Denver, Orlando, San Diego, Las Vegas,
San Antonio, Portland, Charlotte, Nashville, Austin, Jacksonville.

Compiled from public web sources on 2026-07-08 (company sites, market listings,
industry directories). Same caveat as the Florida seed: this is a real, usable
starting list, not the exhaustive permit-level roster — there is no single
national equivalent of Florida's FDOT licensee database, so local operators are
gathered market by market.

For the national workbook the Company fields are repurposed:
  * counties_served     -> which metros the company serves ("nationwide" = all)
  * serves_palm_beach   -> "Yes" = national / multi-market operator (highlighted)
  * city / state        -> the company's HQ / main office
Header labels are overridden accordingly (HEADER_OVERRIDES).
"""
from __future__ import annotations

from typing import List

from .models import (
    Company,
    TYPE_NATIONAL,
    TYPE_REGIONAL,
    TYPE_INDEPENDENT,
    TYPE_MOBILE,
    TYPE_BROKER,
)

# 26 major US OOH markets, listed in market-size rank order (see CITY_MARKET).
TOP_CITIES = [
    "New York", "Los Angeles", "Chicago", "San Francisco", "Atlanta",
    "Washington DC", "Boston", "Dallas", "Houston", "Miami",
    "Philadelphia", "Detroit", "Seattle", "Minneapolis", "Phoenix",
    "Tampa", "Denver", "Orlando", "San Diego", "Las Vegas",
    "San Antonio", "Portland", "Charlotte", "Nashville", "Austin",
    "Jacksonville",
]

_REF = "Static ~$1k–$25k+/4wk; premium/spectacular boards much higher (market avg)"

# Header overrides so the repurposed columns read correctly in the workbook/CSV.
HEADER_OVERRIDES = {
    "counties_served": "Metros Served",
    "serves_palm_beach": "National / multi-market",
    "city": "HQ City",
    "state": "HQ State",
    "primary_market": "Primary Market(s)",
}


NATIONAL_SEED: List[Company] = [
    # ------------------------------------------------------------------ #
    # THE BIG THREE — present in essentially every top-10 city
    # ------------------------------------------------------------------ #
    Company(
        company_name="Lamar Advertising",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (largest US billboard network)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        city="Baton Rouge",
        state="LA",
        website="https://lamar.com/",
        pricing_reference=_REF,
        notes="Largest US OOH operator; ~350k+ displays. Strong in LA, TX, AZ, San Diego (I-5/I-805/I-15/Hwy 78), Jacksonville.",
        source="lamar.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Clear Channel Outdoor",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (top-3 US operator)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        city="San Antonio",
        state="TX",
        website="https://clearchanneloutdoor.com/",
        pricing_reference=_REF,
        notes="Big-three operator; ~$2.1B revenue. e.g. Phoenix ~500 displays reaching 88% of adults 18+ weekly.",
        source="clearchanneloutdoor.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="OUTFRONT Media",
        company_type=TYPE_NATIONAL,
        primary_market="Nationwide (top-3 US operator; major transit)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.outfront.com/",
        pricing_reference=_REF,
        notes="Big-three operator; runs NYC MTA transit advertising. Billboards + transit in all top-10 markets.",
        source="outfront.com; WebSearch 2026-07-08",
        confidence="High",
    ),

    # ------------------------------------------------------------------ #
    # NATIONAL / MULTI-MARKET INDEPENDENTS & PREMIUM NETWORKS
    # ------------------------------------------------------------------ #
    Company(
        company_name="New Tradition Media",
        company_type=TYPE_NATIONAL,
        primary_market="Premium spectaculars: NYC Times Sq, LA Hollywood, Chicago, Portland",
        counties_served="New York; Los Angeles; Chicago; Portland",
        serves_palm_beach="Yes",
        city="Chicago",
        state="IL",
        website="https://www.newtradition.com/",
        pricing_reference="Premium / spectacular placements — quote only, high-end",
        notes="Large-format 'spectacular' billboards in marquee locations (Times Square, Hollywood).",
        source="newtradition.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Capitol Outdoor",
        company_type=TYPE_NATIONAL,
        primary_market="Chicago; Los Angeles; Manhattan; Philadelphia; San Diego; Miami; Washington DC",
        counties_served="New York; Los Angeles; Chicago; Philadelphia; San Diego; Miami; Washington DC",
        serves_palm_beach="Yes",
        website="https://capitoloutdoor.com/",
        pricing_reference=_REF,
        notes="Digital billboards, kiosks, wallscapes across major markets.",
        source="capitoloutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Brooklyn Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA; Los Angeles; Chicago",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://brooklynoutdoor.com/",
        pricing_reference=_REF,
        notes="Woman-owned OOH firm; billboards, wallscapes, experiential.",
        source="brooklynoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Digital Outdoor Advertising, LLC",
        company_type=TYPE_NATIONAL,
        primary_market="Coast-to-coast digital network (200+ markets)",
        counties_served="New York; Philadelphia; Boston; Washington DC; Jacksonville",
        serves_palm_beach="Yes",
        website="https://digitaloutdooradvertising.com/",
        pricing_reference=_REF,
        notes="20,000+ digital & static billboards across 200+ markets incl. Philadelphia and Jacksonville.",
        source="digitaloutdooradvertising.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Becker Boards",
        company_type=TYPE_REGIONAL,
        primary_market="Phoenix (+ SF, Miami, Ft. Lauderdale, Orlando, Chicago)",
        counties_served="Phoenix; Chicago; San Francisco; Miami",
        serves_palm_beach="Yes",
        city="Phoenix",
        state="AZ",
        website="https://www.beckerboards.com/",
        pricing_reference=_REF,
        notes="Digital, static & wallscape billboards; city-wide greater-Phoenix coverage.",
        source="beckerboards.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="AltTerrain",
        company_type=TYPE_MOBILE,
        primary_market="Mobile & street-level: NYC, Chicago, LA",
        counties_served="New York; Chicago; Los Angeles",
        serves_palm_beach="Yes",
        website="https://altterrain.com/",
        pricing_reference="Mobile / street-level placements — quote only",
        notes="Mobile billboards + street-level media (bodegas, laundromats, barbershops).",
        source="altterrain.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ------------------------------------------------------------------ #
    # TEXAS (Houston / Dallas / San Antonio)
    # ------------------------------------------------------------------ #
    Company(
        company_name="SignAd Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Texas (Houston-based) + parts of Louisiana",
        counties_served="Houston; San Antonio; Dallas",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.signad.com/",
        pricing_reference=_REF,
        notes="Largest independently owned OOH company in Texas; 2,600+ displays.",
        source="signad.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="BM Outdoor Media",
        company_type=TYPE_REGIONAL,
        primary_market="44 Texas cities + Phoenix, Austin, Seattle, San Diego, Jacksonville, Detroit, Minneapolis, Charlotte, Tampa",
        counties_served="Houston; Dallas; San Antonio; Phoenix; Austin; Seattle; San Diego; Jacksonville; Detroit; Minneapolis; Charlotte; Tampa",
        serves_palm_beach="No",
        website="https://bmoutdoor.com/",
        pricing_reference=_REF,
        notes="Billboards, digital, transit & street furniture across 44 TX cities and Phoenix.",
        source="bmoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Lux Media",
        company_type=TYPE_MOBILE,
        primary_market="Dallas; Houston; Austin; San Antonio",
        counties_served="Houston; San Antonio; Dallas; Austin",
        serves_palm_beach="No",
        website="https://www.luxmediaads.com/",
        pricing_reference="Mobile LED truck — day/route rate, quote only",
        notes="Mobile LED billboard truck advertising across major TX metros.",
        source="luxmediaads.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Billboards America",
        company_type=TYPE_BROKER,
        primary_market="Texas (Dallas, Houston, Austin, San Antonio, Fort Worth)",
        counties_served="Houston; Dallas; San Antonio",
        serves_palm_beach="No",
        website="https://www.billboardsamerica.com/billboard-advertising-locations/texas",
        pricing_reference=_REF,
        notes="Brokerage with access to prime TX billboard locations.",
        source="billboardsamerica.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Premier Mobile Billboards",
        company_type=TYPE_MOBILE,
        primary_market="Houston; Dallas; San Antonio (mobile)",
        counties_served="Houston; Dallas; San Antonio",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://premiermobilebillboards.com/",
        pricing_reference="Mobile LED truck — quote only",
        notes="Digital billboard trucks across major TX metros (Houston, Dallas, San Antonio).",
        source="premiermobilebillboards.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ------------------------------------------------------------------ #
    # PHOENIX
    # ------------------------------------------------------------------ #
    Company(
        company_name="Arizona Billboard Company",
        company_type=TYPE_INDEPENDENT,
        primary_market="Phoenix / Arizona",
        counties_served="Phoenix",
        serves_palm_beach="No",
        city="Phoenix",
        state="AZ",
        website="https://arizonabillboardcompany.com/",
        pricing_reference=_REF,
        notes="30+ yrs; billboards, digital LED, buses, shelters, airports, stadiums.",
        source="arizonabillboardcompany.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ------------------------------------------------------------------ #
    # SAN DIEGO
    # ------------------------------------------------------------------ #
    Company(
        company_name="American Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="San Diego; Phoenix",
        counties_served="San Diego; Phoenix",
        serves_palm_beach="No",
        website="https://www.americanoutdoor.com/",
        pricing_reference=_REF,
        notes="Digital & static billboards on high-traffic routes; regional operator in San Diego and Phoenix.",
        source="americanoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ------------------------------------------------------------------ #
    # JACKSONVILLE
    # ------------------------------------------------------------------ #
    Company(
        company_name="MediaLease OOH",
        company_type=TYPE_BROKER,
        primary_market="National one-stop OOH (est. early 1980s)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://www.medialeaseooh.com/",
        pricing_reference=_REF,
        notes="One-stop OOH rep in most US metros (Atlanta, Miami, Seattle, Phoenix, "
              "San Diego, San Antonio, LA, Jacksonville…): billboards, rail/bus, shelters, digital.",
        source="medialeaseooh.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # NEW YORK CITY — deep-dive roster (highly fragmented market)
    # ================================================================== #
    Company(
        company_name="JCDecaux",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & street furniture: NYC bus shelters, JFK & LGA airports",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.jcdecaux.com/",
        pricing_reference="Street furniture / airport / transit — quote only",
        notes="Exclusive NYC bus-shelter network + JFK/LGA airport advertising; global OOH leader.",
        source="WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Branded Cities Network",
        company_type=TYPE_NATIONAL,
        primary_market="Times Square spectaculars + major-market landmarks",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        website="https://www.brandedcities.com/",
        pricing_reference="Spectacular / landmark placements — quote only, high-end",
        notes="Operates marquee Times Square spectaculars and other landmark displays.",
        source="WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Intersection",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & smart-city media (LinkNYC kiosks)",
        counties_served="New York; Chicago; Philadelphia",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.intersection.com/",
        pricing_reference="Digital kiosk / transit — quote only",
        notes="Runs LinkNYC kiosk network; transit & place-based media in multiple metros.",
        source="WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="TSX Broadway (TSX Entertainment)",
        company_type=TYPE_INDEPENDENT,
        primary_market="Times Square (single landmark asset)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference="Premium spectacular — quote only, very high-end",
        notes="Flagship 18k-sq-ft curved LED at 47th & Broadway, Times Square.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Neutron Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (digital billboards)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="Digital billboards in NYC's busiest corridors.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Heritage Outdoor Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Times Square digital)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference="Times Square digital — quote only",
        notes="Times Square LED billboard technology.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Pearl Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York / Times Square + experiential",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://pearlmedia.com/",
        pricing_reference="Times Square / experiential — quote only",
        notes="Times Square billboards and experiential activations.",
        source="pearlmedia.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Adams Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Mid-size US markets (13 states); Atlanta; Charlotte",
        counties_served="New York; Atlanta; Charlotte",
        serves_palm_beach="No",
        pricing_reference=_REF,
        notes="One of the largest US OOH firms — 11,000+ units across 13 states; traditional + digital.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Rolling Adz Mobile Billboards",
        company_type=TYPE_MOBILE,
        primary_market="New York City (mobile)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://rollingadz.com/",
        pricing_reference="Mobile billboard — day/route rate, quote only",
        notes="Mobile billboard fleet across NYC.",
        source="rollingadz.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="SILVERCAST Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (spectaculars: Times Sq, Penn Plaza, MSG)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://www.silvercastmedia.com/",
        pricing_reference="Oversized digital/static spectaculars — quote only, high-end",
        notes="Premier oversized billboard spectaculars at Times Sq, Penn Plaza & Madison Square Garden.",
        source="silvercastmedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Colossal Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Brooklyn) — hand-painted murals/wallscapes",
        counties_served="New York",
        serves_palm_beach="No",
        city="Brooklyn",
        state="NY",
        website="https://colossalmedia.com/",
        pricing_reference="Hand-painted wallscape / mural — quote only",
        notes="Specialist in hand-painted outdoor advertising & public-art wallscapes.",
        source="colossalmedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Van Wagner",
        company_type=TYPE_NATIONAL,
        primary_market="Sports & entertainment venue OOH (stadiums/arenas)",
        counties_served="New York; Los Angeles; Chicago",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://www.vanwagner.com/",
        pricing_reference="Venue / sponsorship media — quote only",
        notes="OOH inventory for stadiums, arenas and sports/entertainment facilities.",
        source="vanwagner.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Vector Media",
        company_type=TYPE_NATIONAL,
        primary_market="Transit & experiential (buses, double-deckers)",
        counties_served="New York; Chicago; Philadelphia",
        serves_palm_beach="Yes",
        city="New York",
        state="NY",
        website="https://vectormedia.com/",
        pricing_reference="Transit / experiential — quote only",
        notes="Large-format transit, double-decker buses, experiential assets across US metros.",
        source="vectormedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="PMD Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA (top-5 by spot count)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="Among the top-5 OOH owners in the NYC DMA by spot count.",
        source="oohtoday.com Top-5 NYC operators; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="InSite Street Media",
        company_type=TYPE_REGIONAL,
        primary_market="New York DMA (top-5 by spot count)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://www.insitestreetmedia.com/",
        pricing_reference=_REF,
        notes="Top-5 NYC DMA operator; residential & street-level media networks.",
        source="oohtoday.com Top-5 NYC operators; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Big Outdoor",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York; Philadelphia (digital spectaculars)",
        counties_served="New York; Philadelphia",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://bigoutdoor.com/",
        pricing_reference="Digital spectacular — quote only",
        notes="Digital billboard / spectacular operator (NYC + Philadelphia).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="GSB Digital",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York — wildposting / wheatpaste, print & install",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        website="https://gsbdigital.com/",
        pricing_reference="Wildposting / production — quote only",
        notes="Street-level wheatpaste/wildposting (SoHo, Williamsburg, LES, Bushwick, Harlem) + OOH production & install.",
        source="gsbdigital.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Seen Outdoor Media, LLC",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Brooklyn)",
        counties_served="New York",
        serves_palm_beach="No",
        city="Brooklyn",
        state="NY",
        pricing_reference=_REF,
        notes="On the NYC DOB Active Outdoor Advertising Companies (OAC) registry.",
        source="NYC DOB Active OAC list; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Red Rock Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="New York (Manhattan)",
        counties_served="New York",
        serves_palm_beach="No",
        city="New York",
        state="NY",
        pricing_reference=_REF,
        notes="On the NYC DOB Active Outdoor Advertising Companies (OAC) registry.",
        source="NYC DOB Active OAC list; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Billups",
        company_type=TYPE_BROKER,
        primary_market="National OOH agency / managed services",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://www.billups.com/",
        pricing_reference="Managed-service buying across operators — quote only",
        notes="Independent global OOH agency; plans/buys/measures across all operators & markets.",
        source="billups.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # HOUSTON — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Gilbreath Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Greater Houston + Texas Hill Country",
        counties_served="Houston; San Antonio",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.gilbreathoutdoor.com/",
        pricing_reference=_REF,
        notes="Houston-area operator with a Texas Hill Country satellite office.",
        source="gilbreathoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="MH Outdoor Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="Houston metro",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        pricing_reference=_REF,
        notes="Local Houston billboard operator.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Avail Media Group",
        company_type=TYPE_BROKER,
        primary_market="Houston (independent OOH agency)",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://www.availmediagroup.com/capabilities/out-of-home",
        pricing_reference="Independent agency — negotiates across vendors",
        notes="Independent agency negotiating across multiple Houston OOH vendors for placement & pricing.",
        source="availmediagroup.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Inspiria Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="Houston",
        counties_served="Houston",
        serves_palm_beach="No",
        city="Houston",
        state="TX",
        website="https://inspiriaoutdoor.com/houston-advertising/",
        pricing_reference=_REF,
        notes="Houston billboard advertising across various outdoor formats.",
        source="inspiriaoutdoor.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # DALLAS–FORT WORTH — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Arrington Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Dallas–Fort Worth Metroplex",
        counties_served="Dallas",
        serves_palm_beach="No",
        city="Dallas",
        state="TX",
        website="https://www.arringtonoutdoor.com/",
        pricing_reference=_REF,
        notes="Largest independent billboard company in the DFW area; bulletins & digital.",
        source="arringtonoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Ralston Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Dallas–Fort Worth",
        counties_served="Dallas",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="DFW independent operator (inventory aggregated by AdQuick alongside Lamar/CCO/OUTFRONT).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Albert Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="Dallas–Fort Worth",
        counties_served="Dallas",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="DFW independent operator (named among AdQuick's aggregated DFW operators).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Dallas Billboards LLC",
        company_type=TYPE_BROKER,
        primary_market="Dallas–Fort Worth Metroplex",
        counties_served="Dallas",
        serves_palm_beach="No",
        city="Dallas",
        state="TX",
        website="https://www.dallasbillboards.com/",
        pricing_reference="Media buyer / creative agency — quote only",
        notes="Full-service OOH media buyer & creative agency securing DFW billboard locations.",
        source="dallasbillboards.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # SAN ANTONIO — deep-dive roster
    # ================================================================== #
    Company(
        company_name="True Impact Media",
        company_type=TYPE_BROKER,
        primary_market="San Antonio; San Francisco (+ national mobile)",
        counties_served="San Antonio; San Francisco",
        serves_palm_beach="No",
        website="https://trueimpactmedia.com/billboard-advertising-in-san-antonio/",
        pricing_reference="Billboards + mobile — quote only",
        notes="Comprehensive San Antonio OOH incl. static, digital and mobile billboards.",
        source="trueimpactmedia.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # LOS ANGELES — deep-dive roster (100+ independents in market)
    # ================================================================== #
    Company(
        company_name="Regency Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Los Angeles / Orange County (Sunset Strip, LAX)",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        address="8820 Sunset Blvd",
        city="West Hollywood",
        state="CA",
        zip_code="90069",
        phone="(310) 657-8883",
        website="https://regencyoutdoor.com/",
        pricing_reference="Premium bulletins/spectaculars — quote only, high-end",
        notes="Est. 1974; SoCal's foremost private OOH firm. 300+ billboards & wallscapes, "
              "dominant Sunset Strip presence + LAX exterior. (Sold 35 Strip boards to Netflix for $150M in 2018.)",
        source="regencyoutdoor.com; WebSearch 2026-07-08",
        confidence="High",
    ),
    Company(
        company_name="Bulletin Displays",
        company_type=TYPE_REGIONAL,
        primary_market="Los Angeles (freeway billboards)",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        city="Los Angeles",
        state="CA",
        website="https://www.bulletindisplays.com/",
        pricing_reference=_REF,
        notes="One of the top-5 freeway billboard operators in the LA area; digital & static.",
        source="bulletindisplays.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Bray Outdoor Ads",
        company_type=TYPE_INDEPENDENT,
        primary_market="Los Angeles & San Diego counties (SoCal)",
        counties_served="Los Angeles; San Diego",
        serves_palm_beach="No",
        website="https://brayoutdoor.com/",
        pricing_reference=_REF,
        notes="SoCal billboard operator/media buyer across LA and San Diego counties.",
        source="brayoutdoor.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="O Media Group",
        company_type=TYPE_INDEPENDENT,
        primary_market="Los Angeles",
        counties_served="Los Angeles",
        serves_palm_beach="No",
        city="Los Angeles",
        state="CA",
        pricing_reference=_REF,
        notes="LA independent OOH operator (named among Regency's LA competitors).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # CHICAGO — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Image Media Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Chicagoland",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        website="https://imageoutdoor.com/",
        pricing_reference=_REF,
        notes="Billboard, bulletin, digital & wall advertising across Chicagoland.",
        source="imageoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Outdoor Impact",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (north side)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        website="https://www.outdoorimpact.com/",
        pricing_reference=_REF,
        notes="Billboard & wall-display advertising, esp. northern Chicago.",
        source="outdoorimpact.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="VC Outdoor",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (40 neighborhoods)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference="Wildposting / wallscape / bus wrap — quote only",
        notes="Hotspots, wild postings, wallscapes, bus wraps & street furniture across 40 Chicago neighborhoods.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="GreenSigns Chicago",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago (all-digital network)",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference="Digital billboard — quote only",
        notes="Fully digital, eco-friendly billboard network.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="J&B Signs Inc",
        company_type=TYPE_INDEPENDENT,
        primary_market="Chicago",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference=_REF,
        notes="Independent OOH media company partnering with local/regional/national advertisers.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Red Star Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Chicago",
        counties_served="Chicago",
        serves_palm_beach="No",
        city="Chicago",
        state="IL",
        pricing_reference=_REF,
        notes="Chicago-market billboard operator (named among major Chicago operators).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # PHILADELPHIA — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Keystone Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Philadelphia / Pennsylvania",
        counties_served="Philadelphia",
        serves_palm_beach="No",
        state="PA",
        website="https://www.keystoneoutdoor.com/",
        pricing_reference=_REF,
        notes="Regional PA billboard operator serving the Philadelphia market.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Catalyst Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Philadelphia suburbs + New York",
        counties_served="Philadelphia; New York",
        serves_palm_beach="No",
        state="PA",
        website="https://www.linkedin.com/company/catalyst-outdoor-advertising",
        pricing_reference="Digital billboards — quote only",
        notes="Founded 2009 (Thaddeus Bartkowski); ~14 digital faces, known for 'living wall' "
              "displays. NOTE: financial distress in 2024; assets reportedly being sold to "
              "Lamar & Clear Channel — verify current ownership before contacting.",
        source="Billboard Insider; Philadelphia Inquirer; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # JACKSONVILLE — deep-dive roster
    # ================================================================== #
    Company(
        company_name="Daily Billboards",
        company_type=TYPE_INDEPENDENT,
        primary_market="Jacksonville",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        city="Jacksonville",
        state="FL",
        pricing_reference=_REF,
        notes="Independent operator with ~49 billboard locations in and around Jacksonville.",
        source="Alignable; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="American Mobile Ads",
        company_type=TYPE_MOBILE,
        primary_market="Jacksonville (mobile)",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        website="https://americanmobileads.com/markets/jacksonville",
        pricing_reference="Mobile LED truck — day/route rate, quote only",
        notes="Backlit + digital LED/video mobile billboard trucks in Jacksonville.",
        source="americanmobileads.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Fisher Design & Advertising",
        company_type=TYPE_BROKER,
        primary_market="Jacksonville (agency)",
        counties_served="Jacksonville",
        serves_palm_beach="No",
        city="Jacksonville",
        state="FL",
        website="https://www.fisherdesignandadvertising.com/services/outdoor-advertising-jacksonville/",
        pricing_reference="Agency — books across outdoor vendors, quote only",
        notes="Agency partnering with outdoor companies for Jacksonville OOH campaigns.",
        source="fisherdesignandadvertising.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # ATLANTA
    # ================================================================== #
    Company(
        company_name="Billboard Company Atlanta",
        company_type=TYPE_INDEPENDENT,
        primary_market="Atlanta metro",
        counties_served="Atlanta",
        serves_palm_beach="No",
        city="Atlanta",
        state="GA",
        website="https://billboardcompanyatlanta.com/",
        pricing_reference=_REF,
        notes="Atlanta-area billboard advertising operator.",
        source="billboardcompanyatlanta.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Trailhead Media",
        company_type=TYPE_REGIONAL,
        primary_market="Atlanta / Carolinas / Southeast (digital OOH)",
        counties_served="Atlanta; Charlotte",
        serves_palm_beach="No",
        state="GA",
        website="https://trailheadmedia.com/",
        pricing_reference=_REF,
        notes="Digital billboard & outdoor advertising company.",
        source="trailheadmedia.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # MIAMI
    # ================================================================== #
    Company(
        company_name="SDE Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="Greater Miami",
        counties_served="Miami",
        serves_palm_beach="No",
        city="Miami",
        state="FL",
        website="https://sde-media.com/",
        pricing_reference=_REF,
        notes="Boutique independent; static + digital on Palmetto (SR 826), Dolphin (SR 836) "
              "& Florida's Turnpike. FL Certified Minority Business; Miami-Dade Asset Pool.",
        source="sde-media.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Carter Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="South Florida (Miami / Ft. Lauderdale)",
        counties_served="Miami",
        serves_palm_beach="No",
        website="https://www.carteroutdoor.com/",
        pricing_reference=_REF,
        notes="Family-owned, serving South Florida since 1956.",
        source="carteroutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Plug Talk Media",
        company_type=TYPE_BROKER,
        primary_market="Miami (billboard, DOOH, pDOOH)",
        counties_served="Miami",
        serves_palm_beach="No",
        website="https://www.plugtalk.media/our-markets/miami",
        pricing_reference="Programmatic/DOOH — dynamic",
        notes="Billboard, DOOH and programmatic DOOH campaigns across Miami.",
        source="plugtalk.media; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # WASHINGTON DC
    # ================================================================== #
    Company(
        company_name="Digital Outdoor Advertising — DC",
        company_type=TYPE_REGIONAL,
        primary_market="Washington DC (National Mall, Capitol Hill approaches)",
        counties_served="Washington DC",
        serves_palm_beach="No",
        state="DC",
        website="https://digitaloutdooradvertising.com/",
        pricing_reference=_REF,
        notes="DC-area billboard coverage; supply tightly restricted in the District proper.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # SAN FRANCISCO / BAY AREA
    # ================================================================== #
    Company(
        company_name="Billboard Source",
        company_type=TYPE_BROKER,
        primary_market="San Francisco Bay Area; Los Angeles",
        counties_served="San Francisco; Los Angeles",
        serves_palm_beach="No",
        website="https://www.billboardsource.com/billboard-advertising-in-san-francisco-ca",
        pricing_reference=_REF,
        notes="Outdoor advertising broker for SF/Bay Area and SoCal; works with agencies & individuals.",
        source="billboardsource.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Can't Miss US",
        company_type=TYPE_MOBILE,
        primary_market="National mobile (largest digital-truck fleet)",
        counties_served="San Francisco; Houston; Detroit; Charlotte",
        serves_palm_beach="No",
        website="https://cantmiss.us/",
        pricing_reference="Mobile digital billboard truck — quote only",
        notes="Operates one of the largest fleets of digital billboard trucks in the US.",
        source="cantmiss.us; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # SEATTLE
    # ================================================================== #
    Company(
        company_name="Pacific Outdoor Advertising",
        company_type=TYPE_INDEPENDENT,
        primary_market="Seattle / Western Washington",
        counties_served="Seattle",
        serves_palm_beach="No",
        state="WA",
        website="https://www.pacificoutdooradvertising.com/",
        pricing_reference=_REF,
        notes="Local, boutique Seattle-area billboard company; personalized campaigns.",
        source="pacificoutdooradvertising.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Parker Outdoor Inc.",
        company_type=TYPE_INDEPENDENT,
        primary_market="Seattle metro (Woodinville, Everett)",
        counties_served="Seattle",
        serves_palm_beach="No",
        state="WA",
        website="https://www.parkeroutdoorinc.com/billboards/western-washington/seattle",
        pricing_reference=_REF,
        notes="High-traffic static + digital billboards in Woodinville and Everett.",
        source="parkeroutdoorinc.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Summus Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Seattle / Pacific Northwest",
        counties_served="Seattle",
        serves_palm_beach="No",
        state="WA",
        pricing_reference=_REF,
        notes="Named among the major Seattle-metro OOH operators.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # DENVER
    # ================================================================== #
    Company(
        company_name="Mile High Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Denver metro + Colorado",
        counties_served="Denver",
        serves_palm_beach="No",
        city="Denver",
        state="CO",
        website="https://milehighoutdoor.com/",
        pricing_reference=_REF,
        notes="Est. 1996; Denver's premier independent OOH firm — 400+ metro displays plus "
              "highway boards to Ft. Collins, Colorado Springs, Pueblo, Grand Junction.",
        source="milehighoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Elevation Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Colorado / Wyoming interstates",
        counties_served="Denver",
        serves_palm_beach="No",
        state="CO",
        pricing_reference=_REF,
        notes="Founded 2003; interstate-highway billboard coverage across CO and WY.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Outdoor Ads, Inc.",
        company_type=TYPE_INDEPENDENT,
        primary_market="Denver metro",
        counties_served="Denver",
        serves_palm_beach="No",
        city="Denver",
        state="CO",
        pricing_reference=_REF,
        notes="Billboards, shelters, bus stops and transit displays across the Denver metro.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # AUSTIN
    # ================================================================== #
    Company(
        company_name="Reagan Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Austin (densest local footprint)",
        counties_served="Austin",
        serves_palm_beach="No",
        city="Austin",
        state="TX",
        website="https://www.reaganoutdoor.com/austin/",
        pricing_reference=_REF,
        notes="Austin-headquartered; the largest local billboard operator in the Austin market.",
        source="reaganoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="MediaChoice",
        company_type=TYPE_INDEPENDENT,
        primary_market="Austin",
        counties_served="Austin",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="Significant local Austin OOH operator.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Burkett Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="Austin",
        counties_served="Austin",
        serves_palm_beach="No",
        state="TX",
        pricing_reference=_REF,
        notes="Local Austin billboard operator.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # DETROIT
    # ================================================================== #
    Company(
        company_name="International Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Metro Detroit / Southeast Michigan",
        counties_served="Detroit",
        serves_palm_beach="No",
        city="Detroit",
        state="MI",
        website="https://iobillboard.com/",
        pricing_reference=_REF,
        notes="One of the largest OOH firms in SE Michigan — 100+ billboard faces in Metro Detroit.",
        source="iobillboard.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # MINNEAPOLIS
    # ================================================================== #
    Company(
        company_name="Franklin Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Minnesota / Western Wisconsin",
        counties_served="Minneapolis",
        serves_palm_beach="No",
        state="MN",
        website="https://franklinoutdoor.com/",
        pricing_reference=_REF,
        notes="50+ yrs; deep MN/W-WI roots — 1,000+ fully illuminated billboards.",
        source="franklinoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Blue Ox Media",
        company_type=TYPE_INDEPENDENT,
        primary_market="Minneapolis / Twin Cities (digital)",
        counties_served="Minneapolis",
        serves_palm_beach="No",
        city="Minneapolis",
        state="MN",
        website="https://www.blueoxmediagroup.com/",
        pricing_reference="Digital billboard — quote only",
        notes="Digital displays in the Twin Cities incl. a top-impression board just N of downtown.",
        source="blueoxmediagroup.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # TAMPA
    # ================================================================== #
    Company(
        company_name="Tampa Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Tampa; Lakeland; Winter Haven; Davenport; Sebring",
        counties_served="Tampa",
        serves_palm_beach="No",
        city="Tampa",
        state="FL",
        website="https://tampaoutdoor.com/",
        pricing_reference=_REF,
        notes="Digital & static billboards across Tampa Bay and Central FL.",
        source="tampaoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Signal Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Tampa Bay",
        counties_served="Tampa",
        serves_palm_beach="No",
        state="FL",
        pricing_reference=_REF,
        notes="Named among the major Tampa Bay OOH operators.",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),
    Company(
        company_name="Logan Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Central West Florida (Tampa region)",
        counties_served="Tampa",
        serves_palm_beach="No",
        website="https://loganoutdoor.com/",
        pricing_reference=_REF,
        notes="Covers six central-west FL counties around the Tampa market.",
        source="loganoutdoor.com; WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # ORLANDO
    # ================================================================== #
    Company(
        company_name="Orlando Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Orlando; Lakeland; Winter Haven; Ocala; Davenport; Sebring",
        counties_served="Orlando",
        serves_palm_beach="No",
        city="Orlando",
        state="FL",
        website="https://www.orlandooutdoor.com/",
        pricing_reference=_REF,
        notes="Digital billboards across Orlando and Central FL secondary markets.",
        source="orlandooutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # LAS VEGAS
    # ================================================================== #
    Company(
        company_name="Las Vegas Billboards",
        company_type=TYPE_INDEPENDENT,
        primary_market="Las Vegas metro + Strip",
        counties_served="Las Vegas",
        serves_palm_beach="No",
        city="Las Vegas",
        state="NV",
        website="https://lasvegasbillboards.com/",
        pricing_reference="Strip placements premium — quote only",
        notes="Family-owned, local since 1987; digital & static billboards across the valley & Strip.",
        source="lasvegasbillboards.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # PORTLAND
    # ================================================================== #
    Company(
        company_name="Grapevine Outdoor",
        company_type=TYPE_REGIONAL,
        primary_market="Portland, OR",
        counties_served="Portland",
        serves_palm_beach="No",
        city="Portland",
        state="OR",
        website="https://grapevineoutdoor.com/",
        pricing_reference=_REF,
        notes="Wallscapes, billboards, digital, advertising trikes/trucks & mall signage; local PDX perspective.",
        source="grapevineoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Meadow Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="Pacific Northwest (Portland region)",
        counties_served="Portland",
        serves_palm_beach="No",
        state="OR",
        pricing_reference=_REF,
        notes="Regional PNW billboard operator (inventory aggregated by AdQuick in Portland).",
        source="WebSearch 2026-07-08",
        confidence="Low",
    ),

    # ================================================================== #
    # CHARLOTTE / NASHVILLE (Carolinas & Tennessee)
    # ================================================================== #
    Company(
        company_name="Allison Outdoor Advertising",
        company_type=TYPE_REGIONAL,
        primary_market="North Carolina; Tennessee; Georgia",
        counties_served="Charlotte; Nashville",
        serves_palm_beach="No",
        state="NC",
        website="https://www.allisonoutdoor.com/",
        pricing_reference=_REF,
        notes="Est. 1958; printed & digital billboards across NC/TN/GA incl. the TN Tri-Cities.",
        source="allisonoutdoor.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # NATIONAL BROKERS / MARKETPLACES (book inventory across all listed metros)
    # ================================================================== #
    Company(
        company_name="Fliphound",
        company_type=TYPE_BROKER,
        primary_market="Nationwide self-serve billboard marketplace (600+ markets)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://fliphound.com/",
        pricing_reference="Self-serve; real-time pricing & package rates",
        notes="Online marketplace/network — static & digital billboards across 600+ US markets.",
        source="fliphound.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Billboard Connection",
        company_type=TYPE_BROKER,
        primary_market="Nationwide brokerage franchise (since 1997)",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://billboardconnection.com/",
        pricing_reference="Brokerage — designs, launches & manages OOH campaigns",
        notes="National billboard-advertising franchise; represents outdoor companies in most US markets.",
        source="billboardconnection.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),

    # ================================================================== #
    # OTHER NATIONAL BROKERS / MARKETPLACES
    # ================================================================== #
    Company(
        company_name="AdQuick",
        company_type=TYPE_BROKER,
        primary_market="Nationwide OOH marketplace",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://www.adquick.com/",
        pricing_reference="Marketplace booking; publishes 2026 cost/CPM guides",
        notes="Aggregates operator inventory nationwide; good for live availability & pricing benchmarks.",
        source="adquick.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="Blue Line Media",
        company_type=TYPE_BROKER,
        primary_market="Nationwide brokerage",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        phone="(800) 807-0360",
        email="Advertise@BlueLineMedia.com",
        website="https://www.bluelinemedia.com/",
        pricing_reference="Brokerage; publishes market rate guides",
        notes="Books static & digital billboards across operators in every major market.",
        source="bluelinemedia.com; WebSearch 2026-07-08",
        confidence="Medium",
    ),
    Company(
        company_name="BillboardsIn",
        company_type=TYPE_BROKER,
        primary_market="Nationwide OOH marketplace",
        counties_served="All listed metros (nationwide)",
        serves_palm_beach="Yes",
        website="https://www.billboardsin.com/",
        pricing_reference="Marketplace booking — dynamic",
        notes="Searchable inventory marketplace across US markets.",
        source="billboardsin.com; WebSearch 2026-07-08",
        confidence="Low",
    ),
]


# ---------------------------------------------------------------------- #
# City market ranking — by billboard market size & typical ad rates.
# Ranking is a synthesis of metro/DMA size, OOH inventory density, and the
# published rate ranges below (compiled 2026-07-08). Rates are typical monthly
# ranges for standard billboards; premium/landmark placements run far higher.
# Columns: (rank, city, state, tier, rate_low, rate_high, premium note)
# rate_low / rate_high are typical MONTHLY $ for standard billboards (numeric,
# used for the bar chart); the display string is derived from them.
# ---------------------------------------------------------------------- #
CITY_MARKET = [
    (1, "New York", "NY", "Tier 1 — largest US OOH market", 3000, 50000,
     "Times Square spectaculars $10,000 to $1,000,000+/mo; Manhattan digital $15k–$50k; outer-borough static $3k–$8k."),
    (2, "Los Angeles", "CA", "Tier 1", 2500, 40000,
     "Iconic Sunset Strip bulletins command a large multiple of comparable units 30 mi east."),
    (3, "Chicago", "IL", "Tier 1", 2000, 25000,
     "Premium expressway (Kennedy/Dan Ryan) and Loop digital displays at the high end."),
    (4, "San Francisco", "CA", "Tier 1 — high-cost market", 2500, 30000,
     "Bay Area (SF/Oakland/San Jose); tech-driven demand and scarce inventory keep rates high."),
    (5, "Atlanta", "GA", "Tier 2 — major OOH market", 1500, 16000,
     "Connector/I-285 'Perimeter' corridors; large billboard-friendly metro."),
    (6, "Washington DC", "DC", "Tier 2 — restricted supply", 2000, 20000,
     "Billboards tightly limited in DC proper; value concentrated on MD/VA approaches & transit."),
    (7, "Boston", "MA", "Tier 2", 1800, 18000,
     "OUTFRONT #1 with 675+ digital faces; I-93/Mass Pike and tunnel approaches priced highest."),
    (8, "Dallas", "TX", "Tier 2 — large metro (DFW)", 1500, 18000,
     "High-traffic corridors (I-35, LBJ, Central Expwy) priced highest."),
    (9, "Houston", "TX", "Tier 2 — large metro", 1500, 15000,
     "Clear Channel alone runs 2,000+ boards across 13 counties (99% of DMA adults)."),
    (10, "Miami", "FL", "Tier 2 — high-demand/tourism", 1800, 20000,
     "I-95 / Palmetto / Dolphin Expwy and beach/tourism corridors carry premiums."),
    (11, "Philadelphia", "PA", "Tier 2", 1500, 12000,
     "I-95 / Schuylkill Expwy and Center City digital at the top of range."),
    (12, "Detroit", "MI", "Tier 2/3", 1200, 12000,
     "I-75 / I-94 / M-10 corridors; International Outdoor runs 100+ Metro Detroit faces."),
    (13, "Seattle", "WA", "Tier 2/3", 1500, 14000,
     "Billboard supply constrained by regulation; I-5/I-405 corridors strongest."),
    (14, "Minneapolis", "MN", "Tier 2/3", 1200, 12000,
     "Twin Cities; Franklin Outdoor runs 1,000+ illuminated boards across MN/W-WI."),
    (15, "Phoenix", "AZ", "Tier 2/3", 1200, 10000,
     "Freeway digital (Loop 101/202, I-10); sports-venue-adjacent units premium."),
    (16, "Tampa", "FL", "Tier 3", 1200, 11000,
     "Tampa Bay (Hillsborough/Pinellas); I-4 / I-275 / Veterans Expwy corridors."),
    (17, "Denver", "CO", "Tier 3", 1200, 11000,
     "I-25 / I-70 corridors; Mile High Outdoor runs 400+ metro displays."),
    (18, "Orlando", "FL", "Tier 3 — tourism", 1200, 12000,
     "I-4 / theme-park & tourist corridors carry premiums; strong visitor reach."),
    (19, "San Diego", "CA", "Tier 3", 1500, 10000,
     "I-5 / I-805 / I-15 / Hwy-78 corridors; limited inventory keeps rates firm."),
    (20, "Las Vegas", "NV", "Tier 3 — Strip premium", 1500, 25000,
     "The Strip commands outsized rates (spectaculars far higher); OUTFRONT reaches 99.9% weekly."),
    (21, "San Antonio", "TX", "Tier 3", 1000, 8000,
     "I-10 / Loop 410 / US-281 the strongest placements."),
    (22, "Portland", "OR", "Tier 3", 1200, 11000,
     "Lamar is the largest footprint + sole PDX operator; wallscapes in the Pearl/Downtown."),
    (23, "Charlotte", "NC", "Tier 3", 1000, 9000,
     "I-77 / I-85 / I-485 corridors; Adams Outdoor reaches 1.8M across 22 counties."),
    (24, "Nashville", "TN", "Tier 3 — fast-growing", 1200, 11000,
     "I-40 / I-24 / I-65 and Broadway/tourism demand; Allison Outdoor active regionally."),
    (25, "Austin", "TX", "Tier 3 — fast-growing", 1200, 12000,
     "Reagan Outdoor-dominated; tech-driven demand along I-35 / MoPac / US-183."),
    (26, "Jacksonville", "FL", "Tier 3", 800, 6000,
     "Largest US city by land area; I-95 / I-295 corridors carry the value."),
]

CITY_RANK_DISCLAIMER = (
    "Ranking synthesizes metro/DMA size, billboard inventory density and published "
    "2026 rate guides (AdQuick, DASH TWO, CostCheck, etc.). Rates are typical MONTHLY "
    "ranges for standard billboards; premium/landmark and digital placements run far "
    "higher. Treat as directional benchmarks, not quotes."
)


def cities_for(company: Company) -> List[str]:
    """Which of the listed metros a company serves (from its coverage field).
    A 'nationwide' / 'all listed metros' marker counts as every metro."""
    coverage = (company.counties_served or "")
    low = coverage.lower()
    if "nationwide" in low or "all listed metros" in low:
        return list(TOP_CITIES)
    return [c for c in TOP_CITIES if c in coverage]


def load_national() -> List[Company]:
    return [Company(**{k: v for k, v in vars(c).items()}) for c in NATIONAL_SEED]
