#!/usr/bin/env python3
"""Florida Billboard Company Scraper — CLI.

Collect billboard / out-of-home advertising companies operating in Florida and
export them to an Excel workbook, Palm Beach County first.

Sources (in priority order):
  1. FDOT ODA database  — authoritative list of licensed permit holders (needs
                          open network access to *.fdot.gov)
  2. FOAA member list   — active operators by region
  3. Built-in seed set  — verified companies compiled from public listings, so
                          you always get a usable spreadsheet even offline.

Examples
--------
  # Everything, Palm Beach first (uses seed data; tries live sources too):
  python scraper.py --out data/florida_billboard_companies.xlsx

  # Just Palm Beach County from the live FDOT database:
  python scraper.py --county "Palm Beach" --sources fdot --out palm_beach.xlsx

  # Offline: seed data only, no network calls:
  python scraper.py --sources seed --out florida.xlsx

  # Parse a hand-downloaded FDOT monthly Excel:
  python scraper.py --oda-file ODAData.xlsx --out florida.xlsx
"""
from __future__ import annotations

import argparse
import sys
from typing import List

from fbscraper.models import Company, dedupe
from fbscraper import seed as seed_mod
from fbscraper import excel as excel_mod


def gather(sources: List[str], county: str | None, oda_file: str | None) -> List[Company]:
    companies: List[Company] = []

    if "seed" in sources:
        s = seed_mod.load_seed()
        print(f"[seed] {len(s)} verified companies loaded")
        companies.extend(s)

    if oda_file:
        from fbscraper import fdot
        try:
            parsed = fdot.parse_oda_workbook(oda_file)
            print(f"[fdot] parsed {len(parsed)} companies from {oda_file}")
            companies.extend(parsed)
        except Exception as exc:  # noqa: BLE001
            print(f"[fdot] failed to parse {oda_file}: {exc}", file=sys.stderr)

    if "fdot" in sources:
        from fbscraper import fdot
        cty = county.upper() if county else None
        print("[fdot] contacting FDOT ODA database ...")
        got = fdot.scrape(county=cty)
        print(f"[fdot] {len(got)} companies from FDOT")
        companies.extend(got)

    if "foaa" in sources:
        from fbscraper import foaa
        print("[foaa] contacting FOAA member directory ...")
        got = foaa.scrape()
        print(f"[foaa] {len(got)} companies from FOAA")
        companies.extend(got)

    companies = dedupe(companies)

    if county:
        cu = county.upper()
        # Keep companies that serve the county OR explicitly flag Palm Beach.
        filtered = [
            c for c in companies
            if cu in (c.counties_served or "").upper()
            or cu in (c.primary_market or "").upper()
            or (cu == "PALM BEACH" and (c.serves_palm_beach or "").lower() == "yes")
        ]
        print(f"[filter] {len(filtered)}/{len(companies)} companies match county '{county}'")
        companies = filtered

    return companies


def build_about(sources: List[str], county: str | None, n: int) -> List[str]:
    return [
        "Florida Billboard / Outdoor Advertising Companies",
        f"Generated by fbscraper v1.0 · {n} companies · "
        f"scope: {county or 'all Florida'} · sources: {', '.join(sources)}.",
        "",
        "HOW THE DATA WAS COLLECTED",
        "• Seed set: companies compiled from public web listings, company sites, FOAA "
        "references and industry cost guides (verified 2026-07-08). Palm Beach County "
        "operators are highlighted and listed first.",
        "• FDOT ODA: the authoritative list of state-licensed permit holders. Run the "
        "scraper from an open network (many corporate/cloud networks block *.fdot.gov) "
        "to append every licensed operator statewide with its counties.",
        "• FOAA: the Florida Outdoor Advertising Association member directory by region.",
        "",
        "ABOUT PRICES",
        "• Billboard rates are QUOTE-ONLY — they are not published and vary per specific "
        "board by traffic, size, illumination, static-vs-digital and contract length.",
        "• The 'Pricing Reference' tab gives Florida market-average bands so you can sanity- "
        "check quotes. The per-company pricing column points you to each company's quote/ "
        "booking channel; it does not invent a number.",
        "",
        "CONFIDENCE",
        "• High = name + hard contact detail verified. Medium = name + market verified. "
        "Low = name from a directory, details need confirmation.",
        "",
        "TO EXPAND THIS LIST",
        "  python scraper.py --sources seed,fdot,foaa --out florida_full.xlsx",
        "  (run on a normal network so FDOT/FOAA are reachable)",
    ]


def main() -> int:
    p = argparse.ArgumentParser(description="Scrape Florida billboard companies to Excel.")
    p.add_argument("--out", default="data/florida_billboard_companies.xlsx",
                   help="Output .xlsx path")
    p.add_argument("--county", default=None,
                   help="Filter to a county, e.g. 'Palm Beach'")
    p.add_argument("--sources", default="seed,fdot,foaa",
                   help="Comma list of: seed, fdot, foaa (default: all)")
    p.add_argument("--oda-file", default=None,
                   help="Path to a hand-downloaded FDOT ODA monthly Excel to parse")
    p.add_argument("--csv", nargs="?", const="__auto__", default=None,
                   help="Also write a CSV. Give a path, or pass --csv alone to "
                        "write alongside the .xlsx with a .csv extension.")
    p.add_argument("--dataset", choices=["florida", "national"], default="florida",
                   help="'florida' (default: FDOT/FOAA/seed) or 'national' "
                        "(billboard companies across the top-10 US cities)")
    args = p.parse_args()

    if args.dataset == "national":
        return run_national(args)

    sources = [s.strip().lower() for s in args.sources.split(",") if s.strip()]
    companies = gather(sources, args.county, args.oda_file)

    if not companies:
        print("No companies collected. Try --sources seed for offline data.", file=sys.stderr)
        return 1

    about = build_about(sources, args.county, len(companies))
    path = excel_mod.write_workbook(companies, args.out, about=about)
    pb = sum(1 for c in companies if (c.serves_palm_beach or "").lower() == "yes")
    print(f"\n✓ Wrote {len(companies)} companies ({pb} serving Palm Beach) → {path}")

    if args.csv is not None:
        csv_path = args.csv
        if csv_path == "__auto__":
            csv_path = args.out.rsplit(".", 1)[0] + ".csv"
        excel_mod.write_csv(companies, csv_path)
        print(f"✓ Wrote CSV → {csv_path}")
    return 0


def run_national(args) -> int:
    """Build the top-10-US-cities billboard workbook."""
    from fbscraper import national

    companies = national.load_national()
    print(f"[national] {len(companies)} companies across the top-10 US cities")

    out = args.out
    if out == "data/florida_billboard_companies.xlsx":  # default -> national name
        out = "data/us_top_cities_billboard_companies.xlsx"

    about = [
        "US Top-10 Cities — Billboard / Outdoor Advertising Companies",
        f"Generated by fbscraper v1.0 · {len(companies)} companies · "
        f"cities: {', '.join(national.TOP_CITIES)}.",
        "",
        "SCOPE",
        "• Top-10 US cities by population (city proper): New York, Los Angeles, "
        "Chicago, Houston, Phoenix, Philadelphia, San Antonio, San Diego, Dallas, "
        "Jacksonville.",
        "• 'National / multi-market' companies (the big three plus multi-city "
        "networks) are highlighted and listed first; then market-specific operators.",
        "",
        "DATA & CAVEATS",
        "• Compiled from public web sources on 2026-07-08 (company sites, market "
        "listings, industry directories).",
        "• Unlike Florida (FDOT licensee database), there is NO single national "
        "permit registry, so local operators are gathered market by market and this "
        "list is representative, not exhaustive. Add more per city as needed.",
        "",
        "ABOUT PRICES",
        "• Billboard rates are quote-only and vary per specific board by market, "
        "traffic, size, format and contract length. The Pricing Reference tab gives "
        "market-average bands for sanity-checking quotes; big-city/premium "
        "placements (e.g. Times Square spectaculars) run far above the ranges shown.",
    ]

    path = excel_mod.write_national_workbook(
        companies, out,
        cities=national.TOP_CITIES,
        city_ranking=national.CITY_MARKET,
        ranking_disclaimer=national.CITY_RANK_DISCLAIMER,
        cities_for=national.cities_for,
        about=about,
        header_overrides=national.HEADER_OVERRIDES,
        highlight_key="serves_palm_beach", highlight_match="yes",
    )
    nat = sum(1 for c in companies if (c.serves_palm_beach or "").lower() == "yes")
    print(f"\n✓ Wrote {len(companies)} companies ({nat} national/multi-market) → {path}")
    print("  Tabs: All Companies · City Market Ranking · "
          + " · ".join(national.TOP_CITIES) + " · Pricing · About")
    for city in national.TOP_CITIES:
        n = sum(1 for c in companies if city in national.cities_for(c))
        print(f"    {city:15} {n} companies")

    if args.csv is not None:
        csv_path = args.csv
        if csv_path == "__auto__":
            csv_path = out.rsplit(".", 1)[0] + ".csv"
        excel_mod.write_csv(companies, csv_path, header_overrides=national.HEADER_OVERRIDES)
        print(f"✓ Wrote CSV → {csv_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
